// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: alert_deliveries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAlertDelivery = `-- name: CreateAlertDelivery :one
INSERT INTO alert_deliveries (
    id,
    alert_id,
    channel,
    recipient,
    delivery_kind,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, alert_id, channel, recipient, delivery_kind, status, attempts, last_error, delivered_at, created_at, updated_at
`

type CreateAlertDeliveryParams struct {
	ID           uuid.UUID `json:"id"`
	AlertID      uuid.UUID `json:"alert_id"`
	Channel      string    `json:"channel"`
	Recipient    string    `json:"recipient"`
	DeliveryKind string    `json:"delivery_kind"`
	Status       string    `json:"status"`
}

func (q *Queries) CreateAlertDelivery(ctx context.Context, arg CreateAlertDeliveryParams) (AlertDelivery, error) {
	row := q.db.QueryRow(ctx, createAlertDelivery,
		arg.ID,
		arg.AlertID,
		arg.Channel,
		arg.Recipient,
		arg.DeliveryKind,
		arg.Status,
	)
	var i AlertDelivery
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.Channel,
		&i.Recipient,
		&i.DeliveryKind,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlertDelivery = `-- name: GetAlertDelivery :one
SELECT id, alert_id, channel, recipient, delivery_kind, status, attempts, last_error, delivered_at, created_at, updated_at FROM alert_deliveries
WHERE id = $1
`

func (q *Queries) GetAlertDelivery(ctx context.Context, id uuid.UUID) (AlertDelivery, error) {
	row := q.db.QueryRow(ctx, getAlertDelivery, id)
	var i AlertDelivery
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.Channel,
		&i.Recipient,
		&i.DeliveryKind,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlertDeliveryByTarget = `-- name: GetAlertDeliveryByTarget :one
SELECT id, alert_id, channel, recipient, delivery_kind, status, attempts, last_error, delivered_at, created_at, updated_at FROM alert_deliveries
WHERE alert_id = $1
  AND channel = $2
  AND recipient = $3
  AND delivery_kind = $4
`

type GetAlertDeliveryByTargetParams struct {
	AlertID      uuid.UUID `json:"alert_id"`
	Channel      string    `json:"channel"`
	Recipient    string    `json:"recipient"`
	DeliveryKind string    `json:"delivery_kind"`
}

func (q *Queries) GetAlertDeliveryByTarget(ctx context.Context, arg GetAlertDeliveryByTargetParams) (AlertDelivery, error) {
	row := q.db.QueryRow(ctx, getAlertDeliveryByTarget,
		arg.AlertID,
		arg.Channel,
		arg.Recipient,
		arg.DeliveryKind,
	)
	var i AlertDelivery
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.Channel,
		&i.Recipient,
		&i.DeliveryKind,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementAlertDeliveryAttempt = `-- name: IncrementAlertDeliveryAttempt :one
UPDATE alert_deliveries
SET attempts = attempts + 1,
    updated_at = NOW()
WHERE id = $1
RETURNING id, alert_id, channel, recipient, delivery_kind, status, attempts, last_error, delivered_at, created_at, updated_at
`

func (q *Queries) IncrementAlertDeliveryAttempt(ctx context.Context, id uuid.UUID) (AlertDelivery, error) {
	row := q.db.QueryRow(ctx, incrementAlertDeliveryAttempt, id)
	var i AlertDelivery
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.Channel,
		&i.Recipient,
		&i.DeliveryKind,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlertDeliveries = `-- name: ListAlertDeliveries :many
SELECT id, alert_id, channel, recipient, delivery_kind, status, attempts, last_error, delivered_at, created_at, updated_at
FROM alert_deliveries
WHERE ($1::text IS NULL OR status = $1)
  AND ($2::text IS NULL OR channel = $2)
  AND ($3::uuid IS NULL OR alert_id = $3)
ORDER BY created_at DESC
LIMIT $4
`

type ListAlertDeliveriesParams struct {
	Status   pgtype.Text `json:"status"`
	Channel  pgtype.Text `json:"channel"`
	AlertID  pgtype.UUID `json:"alert_id"`
	RowLimit int32       `json:"row_limit"`
}

func (q *Queries) ListAlertDeliveries(ctx context.Context, arg ListAlertDeliveriesParams) ([]AlertDelivery, error) {
	rows, err := q.db.Query(ctx, listAlertDeliveries,
		arg.Status,
		arg.Channel,
		arg.AlertID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertDelivery{}
	for rows.Next() {
		var i AlertDelivery
		if err := rows.Scan(
			&i.ID,
			&i.AlertID,
			&i.Channel,
			&i.Recipient,
			&i.DeliveryKind,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsNeedingOpenDelivery = `-- name: ListAlertsNeedingOpenDelivery :many
SELECT a.id, a.school_id, a.camera_id, a.alert_type, a.severity, a.status, a.title, a.message, a.metadata, a.opened_at, a.resolved_at, a.created_at, a.updated_at
FROM alerts a
WHERE a.status IN ('OPEN', 'ACKNOWLEDGED')
  AND (
    a.severity = 'CRITICAL'
    OR (
      a.severity = 'WARNING'
      AND a.alert_type IN (
        'CAMERA_FFMPEG_RESTART_SPIKE',
        'CAMERA_UPLOAD_FAILURE_SPIKE',
        'STREAM_WORKER_STALE'
      )
    )
  )
  AND NOT EXISTS (
    SELECT 1
    FROM alert_deliveries d
    WHERE d.alert_id = a.id
      AND d.channel = $1
      AND d.recipient = $2
      AND d.delivery_kind = 'OPENED'
      AND d.status = 'SENT'
  )
ORDER BY a.opened_at ASC
LIMIT $3
`

type ListAlertsNeedingOpenDeliveryParams struct {
	Channel   string `json:"channel"`
	Recipient string `json:"recipient"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) ListAlertsNeedingOpenDelivery(ctx context.Context, arg ListAlertsNeedingOpenDeliveryParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsNeedingOpenDelivery, arg.Channel, arg.Recipient, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.CameraID,
			&i.AlertType,
			&i.Severity,
			&i.Status,
			&i.Title,
			&i.Message,
			&i.Metadata,
			&i.OpenedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAlertDeliveries = `-- name: ListPendingAlertDeliveries :many
SELECT id, alert_id, channel, recipient, delivery_kind, status, attempts, last_error, delivered_at, created_at, updated_at
FROM alert_deliveries
WHERE channel = $1
  AND status IN ('PENDING', 'FAILED')
  AND attempts < $2
ORDER BY created_at ASC
LIMIT $3
`

type ListPendingAlertDeliveriesParams struct {
	Channel  string `json:"channel"`
	Attempts int32  `json:"attempts"`
	Limit    int32  `json:"limit"`
}

func (q *Queries) ListPendingAlertDeliveries(ctx context.Context, arg ListPendingAlertDeliveriesParams) ([]AlertDelivery, error) {
	rows, err := q.db.Query(ctx, listPendingAlertDeliveries, arg.Channel, arg.Attempts, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertDelivery{}
	for rows.Next() {
		var i AlertDelivery
		if err := rows.Scan(
			&i.ID,
			&i.AlertID,
			&i.Channel,
			&i.Recipient,
			&i.DeliveryKind,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResolvedAlertsNeedingDelivery = `-- name: ListResolvedAlertsNeedingDelivery :many
SELECT a.id, a.school_id, a.camera_id, a.alert_type, a.severity, a.status, a.title, a.message, a.metadata, a.opened_at, a.resolved_at, a.created_at, a.updated_at
FROM alerts a
WHERE a.status = 'RESOLVED'
  AND a.resolved_at IS NOT NULL
  AND EXISTS (
    SELECT 1
    FROM alert_deliveries d
    WHERE d.alert_id = a.id
      AND d.channel = $1
      AND d.recipient = $2
      AND d.delivery_kind = 'OPENED'
      AND d.status = 'SENT'
  )
  AND NOT EXISTS (
    SELECT 1
    FROM alert_deliveries d
    WHERE d.alert_id = a.id
      AND d.channel = $1
      AND d.recipient = $2
      AND d.delivery_kind = 'RESOLVED'
      AND d.status = 'SENT'
  )
ORDER BY a.resolved_at ASC
LIMIT $3
`

type ListResolvedAlertsNeedingDeliveryParams struct {
	Channel   string `json:"channel"`
	Recipient string `json:"recipient"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) ListResolvedAlertsNeedingDelivery(ctx context.Context, arg ListResolvedAlertsNeedingDeliveryParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listResolvedAlertsNeedingDelivery, arg.Channel, arg.Recipient, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.CameraID,
			&i.AlertType,
			&i.Severity,
			&i.Status,
			&i.Title,
			&i.Message,
			&i.Metadata,
			&i.OpenedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAlertDeliveryFailed = `-- name: MarkAlertDeliveryFailed :one
UPDATE alert_deliveries
SET status = 'FAILED',
    last_error = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, alert_id, channel, recipient, delivery_kind, status, attempts, last_error, delivered_at, created_at, updated_at
`

type MarkAlertDeliveryFailedParams struct {
	ID        uuid.UUID   `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkAlertDeliveryFailed(ctx context.Context, arg MarkAlertDeliveryFailedParams) (AlertDelivery, error) {
	row := q.db.QueryRow(ctx, markAlertDeliveryFailed, arg.ID, arg.LastError)
	var i AlertDelivery
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.Channel,
		&i.Recipient,
		&i.DeliveryKind,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markAlertDeliverySent = `-- name: MarkAlertDeliverySent :one
UPDATE alert_deliveries
SET status = 'SENT',
    delivered_at = NOW(),
    updated_at = NOW(),
    last_error = NULL
WHERE id = $1
RETURNING id, alert_id, channel, recipient, delivery_kind, status, attempts, last_error, delivered_at, created_at, updated_at
`

func (q *Queries) MarkAlertDeliverySent(ctx context.Context, id uuid.UUID) (AlertDelivery, error) {
	row := q.db.QueryRow(ctx, markAlertDeliverySent, id)
	var i AlertDelivery
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.Channel,
		&i.Recipient,
		&i.DeliveryKind,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markAlertDeliverySkipped = `-- name: MarkAlertDeliverySkipped :one
UPDATE alert_deliveries
SET status = 'SKIPPED',
    last_error = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, alert_id, channel, recipient, delivery_kind, status, attempts, last_error, delivered_at, created_at, updated_at
`

type MarkAlertDeliverySkippedParams struct {
	ID        uuid.UUID   `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkAlertDeliverySkipped(ctx context.Context, arg MarkAlertDeliverySkippedParams) (AlertDelivery, error) {
	row := q.db.QueryRow(ctx, markAlertDeliverySkipped, arg.ID, arg.LastError)
	var i AlertDelivery
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.Channel,
		&i.Recipient,
		&i.DeliveryKind,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
