// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: billing.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approvePayment = `-- name: ApprovePayment :one
UPDATE payments
SET status = 'APPROVED',
    approved_by = $2,
    approved_at = NOW(),
    notes = COALESCE($3, notes),
    updated_at = NOW()
WHERE id = $1 AND status = 'PENDING'
RETURNING id, parent_id, school_id, subscription_id, amount_cents, currency, method, status, reference, proof_url, notes, approved_by, approved_at, rejected_by, rejected_at, created_at, updated_at
`

type ApprovePaymentParams struct {
	ID         uuid.UUID   `json:"id"`
	ApprovedBy pgtype.UUID `json:"approved_by"`
	Notes      pgtype.Text `json:"notes"`
}

func (q *Queries) ApprovePayment(ctx context.Context, arg ApprovePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, approvePayment, arg.ID, arg.ApprovedBy, arg.Notes)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.SubscriptionID,
		&i.AmountCents,
		&i.Currency,
		&i.Method,
		&i.Status,
		&i.Reference,
		&i.ProofUrl,
		&i.Notes,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const closeSchoolRevenueShares = `-- name: CloseSchoolRevenueShares :execrows
UPDATE school_revenue_share
SET active_to = $2, updated_at = NOW()
WHERE school_id = $1
  AND (active_to IS NULL OR active_to > $2)
`

type CloseSchoolRevenueSharesParams struct {
	SchoolID uuid.UUID   `json:"school_id"`
	ActiveTo pgtype.Date `json:"active_to"`
}

func (q *Queries) CloseSchoolRevenueShares(ctx context.Context, arg CloseSchoolRevenueSharesParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeSchoolRevenueShares, arg.SchoolID, arg.ActiveTo)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countInvoicesForDatePrefix = `-- name: CountInvoicesForDatePrefix :one
SELECT COUNT(*)::bigint
FROM invoices
WHERE invoice_number LIKE $1
`

func (q *Queries) CountInvoicesForDatePrefix(ctx context.Context, invoiceNumber string) (int64, error) {
	row := q.db.QueryRow(ctx, countInvoicesForDatePrefix, invoiceNumber)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
    id,
    parent_id,
    school_id,
    subscription_id,
    invoice_number,
    amount_cents,
    currency,
    status,
    due_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, parent_id, school_id, subscription_id, invoice_number, amount_cents, currency, status, due_date, paid_at, created_at, updated_at
`

type CreateInvoiceParams struct {
	ID             uuid.UUID   `json:"id"`
	ParentID       pgtype.UUID `json:"parent_id"`
	SchoolID       pgtype.UUID `json:"school_id"`
	SubscriptionID pgtype.UUID `json:"subscription_id"`
	InvoiceNumber  string      `json:"invoice_number"`
	AmountCents    int64       `json:"amount_cents"`
	Currency       string      `json:"currency"`
	Status         string      `json:"status"`
	DueDate        pgtype.Date `json:"due_date"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.ID,
		arg.ParentID,
		arg.SchoolID,
		arg.SubscriptionID,
		arg.InvoiceNumber,
		arg.AmountCents,
		arg.Currency,
		arg.Status,
		arg.DueDate,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.SubscriptionID,
		&i.InvoiceNumber,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.DueDate,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    id,
    parent_id,
    school_id,
    subscription_id,
    amount_cents,
    currency,
    method,
    status,
    reference,
    proof_url,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, parent_id, school_id, subscription_id, amount_cents, currency, method, status, reference, proof_url, notes, approved_by, approved_at, rejected_by, rejected_at, created_at, updated_at
`

type CreatePaymentParams struct {
	ID             uuid.UUID   `json:"id"`
	ParentID       pgtype.UUID `json:"parent_id"`
	SchoolID       pgtype.UUID `json:"school_id"`
	SubscriptionID pgtype.UUID `json:"subscription_id"`
	AmountCents    int64       `json:"amount_cents"`
	Currency       string      `json:"currency"`
	Method         string      `json:"method"`
	Status         string      `json:"status"`
	Reference      pgtype.Text `json:"reference"`
	ProofUrl       pgtype.Text `json:"proof_url"`
	Notes          pgtype.Text `json:"notes"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ID,
		arg.ParentID,
		arg.SchoolID,
		arg.SubscriptionID,
		arg.AmountCents,
		arg.Currency,
		arg.Method,
		arg.Status,
		arg.Reference,
		arg.ProofUrl,
		arg.Notes,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.SubscriptionID,
		&i.AmountCents,
		&i.Currency,
		&i.Method,
		&i.Status,
		&i.Reference,
		&i.ProofUrl,
		&i.Notes,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSchoolRevenueShare = `-- name: CreateSchoolRevenueShare :one
INSERT INTO school_revenue_share (
    id,
    school_id,
    percentage,
    active_from,
    active_to
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, school_id, percentage, active_from, active_to, created_at, updated_at
`

type CreateSchoolRevenueShareParams struct {
	ID         uuid.UUID      `json:"id"`
	SchoolID   uuid.UUID      `json:"school_id"`
	Percentage pgtype.Numeric `json:"percentage"`
	ActiveFrom pgtype.Date    `json:"active_from"`
	ActiveTo   pgtype.Date    `json:"active_to"`
}

func (q *Queries) CreateSchoolRevenueShare(ctx context.Context, arg CreateSchoolRevenueShareParams) (SchoolRevenueShare, error) {
	row := q.db.QueryRow(ctx, createSchoolRevenueShare,
		arg.ID,
		arg.SchoolID,
		arg.Percentage,
		arg.ActiveFrom,
		arg.ActiveTo,
	)
	var i SchoolRevenueShare
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Percentage,
		&i.ActiveFrom,
		&i.ActiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOpenInvoiceForParentSchool = `-- name: FindOpenInvoiceForParentSchool :one
SELECT id, parent_id, school_id, subscription_id, invoice_number, amount_cents, currency, status, due_date, paid_at, created_at, updated_at
FROM invoices
WHERE parent_id = $1
  AND school_id = $2
  AND status IN ('OPEN', 'OVERDUE')
ORDER BY created_at DESC
LIMIT 1
`

type FindOpenInvoiceForParentSchoolParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	SchoolID pgtype.UUID `json:"school_id"`
}

func (q *Queries) FindOpenInvoiceForParentSchool(ctx context.Context, arg FindOpenInvoiceForParentSchoolParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, findOpenInvoiceForParentSchool, arg.ParentID, arg.SchoolID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.SubscriptionID,
		&i.InvoiceNumber,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.DueDate,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveSchoolRevenueShare = `-- name: GetActiveSchoolRevenueShare :one
SELECT id, school_id, percentage, active_from, active_to, created_at, updated_at
FROM school_revenue_share
WHERE school_id = $1
  AND active_from <= CURRENT_DATE
  AND (active_to IS NULL OR active_to >= CURRENT_DATE)
ORDER BY active_from DESC
LIMIT 1
`

func (q *Queries) GetActiveSchoolRevenueShare(ctx context.Context, schoolID uuid.UUID) (SchoolRevenueShare, error) {
	row := q.db.QueryRow(ctx, getActiveSchoolRevenueShare, schoolID)
	var i SchoolRevenueShare
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Percentage,
		&i.ActiveFrom,
		&i.ActiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, parent_id, school_id, subscription_id, invoice_number, amount_cents, currency, status, due_date, paid_at, created_at, updated_at FROM invoices WHERE id = $1
`

func (q *Queries) GetInvoice(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.SubscriptionID,
		&i.InvoiceNumber,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.DueDate,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceByNumber = `-- name: GetInvoiceByNumber :one
SELECT id, parent_id, school_id, subscription_id, invoice_number, amount_cents, currency, status, due_date, paid_at, created_at, updated_at FROM invoices WHERE invoice_number = $1
`

func (q *Queries) GetInvoiceByNumber(ctx context.Context, invoiceNumber string) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByNumber, invoiceNumber)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.SubscriptionID,
		&i.InvoiceNumber,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.DueDate,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, parent_id, school_id, subscription_id, amount_cents, currency, method, status, reference, proof_url, notes, approved_by, approved_at, rejected_by, rejected_at, created_at, updated_at FROM payments WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.SubscriptionID,
		&i.AmountCents,
		&i.Currency,
		&i.Method,
		&i.Status,
		&i.Reference,
		&i.ProofUrl,
		&i.Notes,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvoices = `-- name: ListInvoices :many
SELECT i.id, i.parent_id, i.school_id, i.subscription_id, i.invoice_number, i.amount_cents, i.currency, i.status, i.due_date, i.paid_at, i.created_at, i.updated_at, u.full_name AS parent_name, sch.name AS school_name
FROM invoices i
LEFT JOIN users u ON u.id = i.parent_id
LEFT JOIN schools sch ON sch.id = i.school_id
WHERE ($1::uuid[] IS NULL OR i.school_id = ANY($1::uuid[]))
  AND ($2::uuid IS NULL OR i.school_id = $2)
  AND ($3::uuid IS NULL OR i.parent_id = $3)
  AND ($4::text IS NULL OR i.status = $4)
ORDER BY i.created_at DESC
LIMIT $5
`

type ListInvoicesParams struct {
	SchoolIds []uuid.UUID `json:"school_ids"`
	SchoolID  pgtype.UUID `json:"school_id"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Status    pgtype.Text `json:"status"`
	RowLimit  int32       `json:"row_limit"`
}

type ListInvoicesRow struct {
	ID             uuid.UUID          `json:"id"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	SchoolID       pgtype.UUID        `json:"school_id"`
	SubscriptionID pgtype.UUID        `json:"subscription_id"`
	InvoiceNumber  string             `json:"invoice_number"`
	AmountCents    int64              `json:"amount_cents"`
	Currency       string             `json:"currency"`
	Status         string             `json:"status"`
	DueDate        pgtype.Date        `json:"due_date"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ParentName     pgtype.Text        `json:"parent_name"`
	SchoolName     pgtype.Text        `json:"school_name"`
}

func (q *Queries) ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]ListInvoicesRow, error) {
	rows, err := q.db.Query(ctx, listInvoices,
		arg.SchoolIds,
		arg.SchoolID,
		arg.ParentID,
		arg.Status,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoicesRow{}
	for rows.Next() {
		var i ListInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.SchoolID,
			&i.SubscriptionID,
			&i.InvoiceNumber,
			&i.AmountCents,
			&i.Currency,
			&i.Status,
			&i.DueDate,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentName,
			&i.SchoolName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesForParent = `-- name: ListInvoicesForParent :many
SELECT i.id, i.parent_id, i.school_id, i.subscription_id, i.invoice_number, i.amount_cents, i.currency, i.status, i.due_date, i.paid_at, i.created_at, i.updated_at, sch.name AS school_name
FROM invoices i
LEFT JOIN schools sch ON sch.id = i.school_id
WHERE i.parent_id = $1
ORDER BY i.created_at DESC
LIMIT $2
`

type ListInvoicesForParentParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	Limit    int32       `json:"limit"`
}

type ListInvoicesForParentRow struct {
	ID             uuid.UUID          `json:"id"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	SchoolID       pgtype.UUID        `json:"school_id"`
	SubscriptionID pgtype.UUID        `json:"subscription_id"`
	InvoiceNumber  string             `json:"invoice_number"`
	AmountCents    int64              `json:"amount_cents"`
	Currency       string             `json:"currency"`
	Status         string             `json:"status"`
	DueDate        pgtype.Date        `json:"due_date"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	SchoolName     pgtype.Text        `json:"school_name"`
}

func (q *Queries) ListInvoicesForParent(ctx context.Context, arg ListInvoicesForParentParams) ([]ListInvoicesForParentRow, error) {
	rows, err := q.db.Query(ctx, listInvoicesForParent, arg.ParentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvoicesForParentRow{}
	for rows.Next() {
		var i ListInvoicesForParentRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.SchoolID,
			&i.SubscriptionID,
			&i.InvoiceNumber,
			&i.AmountCents,
			&i.Currency,
			&i.Status,
			&i.DueDate,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SchoolName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayments = `-- name: ListPayments :many
SELECT p.id, p.parent_id, p.school_id, p.subscription_id, p.amount_cents, p.currency, p.method, p.status, p.reference, p.proof_url, p.notes, p.approved_by, p.approved_at, p.rejected_by, p.rejected_at, p.created_at, p.updated_at, u.full_name AS parent_name, sch.name AS school_name
FROM payments p
LEFT JOIN users u ON u.id = p.parent_id
LEFT JOIN schools sch ON sch.id = p.school_id
WHERE ($1::uuid[] IS NULL OR p.school_id = ANY($1::uuid[]))
  AND ($2::uuid IS NULL OR p.school_id = $2)
  AND ($3::uuid IS NULL OR p.parent_id = $3)
  AND ($4::text IS NULL OR p.status = $4)
  AND ($5::text IS NULL OR p.method = $5)
ORDER BY p.created_at DESC
LIMIT $6
`

type ListPaymentsParams struct {
	SchoolIds []uuid.UUID `json:"school_ids"`
	SchoolID  pgtype.UUID `json:"school_id"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Status    pgtype.Text `json:"status"`
	Method    pgtype.Text `json:"method"`
	RowLimit  int32       `json:"row_limit"`
}

type ListPaymentsRow struct {
	ID             uuid.UUID          `json:"id"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	SchoolID       pgtype.UUID        `json:"school_id"`
	SubscriptionID pgtype.UUID        `json:"subscription_id"`
	AmountCents    int64              `json:"amount_cents"`
	Currency       string             `json:"currency"`
	Method         string             `json:"method"`
	Status         string             `json:"status"`
	Reference      pgtype.Text        `json:"reference"`
	ProofUrl       pgtype.Text        `json:"proof_url"`
	Notes          pgtype.Text        `json:"notes"`
	ApprovedBy     pgtype.UUID        `json:"approved_by"`
	ApprovedAt     pgtype.Timestamptz `json:"approved_at"`
	RejectedBy     pgtype.UUID        `json:"rejected_by"`
	RejectedAt     pgtype.Timestamptz `json:"rejected_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ParentName     pgtype.Text        `json:"parent_name"`
	SchoolName     pgtype.Text        `json:"school_name"`
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]ListPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listPayments,
		arg.SchoolIds,
		arg.SchoolID,
		arg.ParentID,
		arg.Status,
		arg.Method,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentsRow{}
	for rows.Next() {
		var i ListPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.SchoolID,
			&i.SubscriptionID,
			&i.AmountCents,
			&i.Currency,
			&i.Method,
			&i.Status,
			&i.Reference,
			&i.ProofUrl,
			&i.Notes,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.RejectedBy,
			&i.RejectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentName,
			&i.SchoolName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsForParent = `-- name: ListPaymentsForParent :many
SELECT p.id, p.parent_id, p.school_id, p.subscription_id, p.amount_cents, p.currency, p.method, p.status, p.reference, p.proof_url, p.notes, p.approved_by, p.approved_at, p.rejected_by, p.rejected_at, p.created_at, p.updated_at, sch.name AS school_name
FROM payments p
LEFT JOIN schools sch ON sch.id = p.school_id
WHERE p.parent_id = $1
ORDER BY p.created_at DESC
LIMIT $2
`

type ListPaymentsForParentParams struct {
	ParentID pgtype.UUID `json:"parent_id"`
	Limit    int32       `json:"limit"`
}

type ListPaymentsForParentRow struct {
	ID             uuid.UUID          `json:"id"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	SchoolID       pgtype.UUID        `json:"school_id"`
	SubscriptionID pgtype.UUID        `json:"subscription_id"`
	AmountCents    int64              `json:"amount_cents"`
	Currency       string             `json:"currency"`
	Method         string             `json:"method"`
	Status         string             `json:"status"`
	Reference      pgtype.Text        `json:"reference"`
	ProofUrl       pgtype.Text        `json:"proof_url"`
	Notes          pgtype.Text        `json:"notes"`
	ApprovedBy     pgtype.UUID        `json:"approved_by"`
	ApprovedAt     pgtype.Timestamptz `json:"approved_at"`
	RejectedBy     pgtype.UUID        `json:"rejected_by"`
	RejectedAt     pgtype.Timestamptz `json:"rejected_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	SchoolName     pgtype.Text        `json:"school_name"`
}

func (q *Queries) ListPaymentsForParent(ctx context.Context, arg ListPaymentsForParentParams) ([]ListPaymentsForParentRow, error) {
	rows, err := q.db.Query(ctx, listPaymentsForParent, arg.ParentID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentsForParentRow{}
	for rows.Next() {
		var i ListPaymentsForParentRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.SchoolID,
			&i.SubscriptionID,
			&i.AmountCents,
			&i.Currency,
			&i.Method,
			&i.Status,
			&i.Reference,
			&i.ProofUrl,
			&i.Notes,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.RejectedBy,
			&i.RejectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SchoolName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchoolRevenueShares = `-- name: ListSchoolRevenueShares :many
SELECT id, school_id, percentage, active_from, active_to, created_at, updated_at
FROM school_revenue_share
WHERE school_id = $1
ORDER BY active_from DESC
`

func (q *Queries) ListSchoolRevenueShares(ctx context.Context, schoolID uuid.UUID) ([]SchoolRevenueShare, error) {
	rows, err := q.db.Query(ctx, listSchoolRevenueShares, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SchoolRevenueShare{}
	for rows.Next() {
		var i SchoolRevenueShare
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Percentage,
			&i.ActiveFrom,
			&i.ActiveTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvoicePaid = `-- name: MarkInvoicePaid :one
UPDATE invoices
SET status = 'PAID', paid_at = NOW(), updated_at = NOW()
WHERE id = $1 AND status IN ('OPEN', 'OVERDUE')
RETURNING id, parent_id, school_id, subscription_id, invoice_number, amount_cents, currency, status, due_date, paid_at, created_at, updated_at
`

func (q *Queries) MarkInvoicePaid(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, markInvoicePaid, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.SubscriptionID,
		&i.InvoiceNumber,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.DueDate,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rejectPayment = `-- name: RejectPayment :one
UPDATE payments
SET status = 'REJECTED',
    rejected_by = $2,
    rejected_at = NOW(),
    notes = COALESCE($3, notes),
    updated_at = NOW()
WHERE id = $1 AND status = 'PENDING'
RETURNING id, parent_id, school_id, subscription_id, amount_cents, currency, method, status, reference, proof_url, notes, approved_by, approved_at, rejected_by, rejected_at, created_at, updated_at
`

type RejectPaymentParams struct {
	ID         uuid.UUID   `json:"id"`
	RejectedBy pgtype.UUID `json:"rejected_by"`
	Notes      pgtype.Text `json:"notes"`
}

func (q *Queries) RejectPayment(ctx context.Context, arg RejectPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, rejectPayment, arg.ID, arg.RejectedBy, arg.Notes)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.SubscriptionID,
		&i.AmountCents,
		&i.Currency,
		&i.Method,
		&i.Status,
		&i.Reference,
		&i.ProofUrl,
		&i.Notes,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectedBy,
		&i.RejectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const voidInvoice = `-- name: VoidInvoice :one
UPDATE invoices
SET status = 'VOID', updated_at = NOW()
WHERE id = $1 AND status IN ('OPEN', 'OVERDUE')
RETURNING id, parent_id, school_id, subscription_id, invoice_number, amount_cents, currency, status, due_date, paid_at, created_at, updated_at
`

func (q *Queries) VoidInvoice(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, voidInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.SubscriptionID,
		&i.InvoiceNumber,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.DueDate,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
