// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cameras.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cameraBelongsToSchool = `-- name: CameraBelongsToSchool :one
SELECT EXISTS (
    SELECT 1 FROM cameras
    WHERE id = $1 AND school_id = $2
) AS belongs
`

type CameraBelongsToSchoolParams struct {
	ID       uuid.UUID `json:"id"`
	SchoolID uuid.UUID `json:"school_id"`
}

func (q *Queries) CameraBelongsToSchool(ctx context.Context, arg CameraBelongsToSchoolParams) (bool, error) {
	row := q.db.QueryRow(ctx, cameraBelongsToSchool, arg.ID, arg.SchoolID)
	var belongs bool
	err := row.Scan(&belongs)
	return belongs, err
}

const createCamera = `-- name: CreateCamera :one
INSERT INTO cameras (
    id,
    school_id,
    classroom_id,
    name,
    encrypted_rtsp_url,
    r2_live_path,
    r2_recording_path,
    default_quality,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, school_id, classroom_id, name, encrypted_rtsp_url, r2_live_path, r2_recording_path, default_quality, status, last_segment_at, created_at, updated_at
`

type CreateCameraParams struct {
	ID               uuid.UUID   `json:"id"`
	SchoolID         uuid.UUID   `json:"school_id"`
	ClassroomID      pgtype.UUID `json:"classroom_id"`
	Name             string      `json:"name"`
	EncryptedRtspUrl pgtype.Text `json:"encrypted_rtsp_url"`
	R2LivePath       string      `json:"r2_live_path"`
	R2RecordingPath  pgtype.Text `json:"r2_recording_path"`
	DefaultQuality   string      `json:"default_quality"`
	Status           string      `json:"status"`
}

func (q *Queries) CreateCamera(ctx context.Context, arg CreateCameraParams) (Camera, error) {
	row := q.db.QueryRow(ctx, createCamera,
		arg.ID,
		arg.SchoolID,
		arg.ClassroomID,
		arg.Name,
		arg.EncryptedRtspUrl,
		arg.R2LivePath,
		arg.R2RecordingPath,
		arg.DefaultQuality,
		arg.Status,
	)
	var i Camera
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.ClassroomID,
		&i.Name,
		&i.EncryptedRtspUrl,
		&i.R2LivePath,
		&i.R2RecordingPath,
		&i.DefaultQuality,
		&i.Status,
		&i.LastSegmentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCamera = `-- name: GetCamera :one
SELECT id, school_id, classroom_id, name, encrypted_rtsp_url, r2_live_path, r2_recording_path, default_quality, status, last_segment_at, created_at, updated_at FROM cameras
WHERE id = $1
`

func (q *Queries) GetCamera(ctx context.Context, id uuid.UUID) (Camera, error) {
	row := q.db.QueryRow(ctx, getCamera, id)
	var i Camera
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.ClassroomID,
		&i.Name,
		&i.EncryptedRtspUrl,
		&i.R2LivePath,
		&i.R2RecordingPath,
		&i.DefaultQuality,
		&i.Status,
		&i.LastSegmentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCamerasByClassroom = `-- name: ListCamerasByClassroom :many
SELECT id, school_id, classroom_id, name, encrypted_rtsp_url, r2_live_path, r2_recording_path, default_quality, status, last_segment_at, created_at, updated_at FROM cameras
WHERE classroom_id = $1
ORDER BY name
`

func (q *Queries) ListCamerasByClassroom(ctx context.Context, classroomID pgtype.UUID) ([]Camera, error) {
	rows, err := q.db.Query(ctx, listCamerasByClassroom, classroomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Camera{}
	for rows.Next() {
		var i Camera
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.ClassroomID,
			&i.Name,
			&i.EncryptedRtspUrl,
			&i.R2LivePath,
			&i.R2RecordingPath,
			&i.DefaultQuality,
			&i.Status,
			&i.LastSegmentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCamerasBySchool = `-- name: ListCamerasBySchool :many
SELECT id, school_id, classroom_id, name, encrypted_rtsp_url, r2_live_path, r2_recording_path, default_quality, status, last_segment_at, created_at, updated_at FROM cameras
WHERE school_id = $1
ORDER BY name
`

func (q *Queries) ListCamerasBySchool(ctx context.Context, schoolID uuid.UUID) ([]Camera, error) {
	rows, err := q.db.Query(ctx, listCamerasBySchool, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Camera{}
	for rows.Next() {
		var i Camera
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.ClassroomID,
			&i.Name,
			&i.EncryptedRtspUrl,
			&i.R2LivePath,
			&i.R2RecordingPath,
			&i.DefaultQuality,
			&i.Status,
			&i.LastSegmentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCamerasForParent = `-- name: ListCamerasForParent :many
SELECT DISTINCT
    cam.id AS camera_id,
    cam.name AS camera_name,
    cam.default_quality,
    cam.status,
    s.name AS school_name,
    cr.name AS classroom_name
FROM cameras cam
INNER JOIN schools s ON s.id = cam.school_id
LEFT JOIN classrooms cr ON cr.id = cam.classroom_id
INNER JOIN children ch ON ch.classroom_id = cam.classroom_id
INNER JOIN parent_children pc ON pc.child_id = ch.id
WHERE pc.parent_id = $1
  AND cam.classroom_id IS NOT NULL
ORDER BY cam.name
`

type ListCamerasForParentRow struct {
	CameraID       uuid.UUID   `json:"camera_id"`
	CameraName     string      `json:"camera_name"`
	DefaultQuality string      `json:"default_quality"`
	Status         string      `json:"status"`
	SchoolName     string      `json:"school_name"`
	ClassroomName  pgtype.Text `json:"classroom_name"`
}

func (q *Queries) ListCamerasForParent(ctx context.Context, parentID uuid.UUID) ([]ListCamerasForParentRow, error) {
	rows, err := q.db.Query(ctx, listCamerasForParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCamerasForParentRow{}
	for rows.Next() {
		var i ListCamerasForParentRow
		if err := rows.Scan(
			&i.CameraID,
			&i.CameraName,
			&i.DefaultQuality,
			&i.Status,
			&i.SchoolName,
			&i.ClassroomName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCamera = `-- name: UpdateCamera :one
UPDATE cameras
SET
    name = COALESCE($1, name),
    classroom_id = COALESCE($2, classroom_id),
    encrypted_rtsp_url = COALESCE($3, encrypted_rtsp_url),
    r2_live_path = COALESCE($4, r2_live_path),
    r2_recording_path = COALESCE($5, r2_recording_path),
    default_quality = COALESCE($6, default_quality),
    status = COALESCE($7, status),
    updated_at = NOW()
WHERE id = $8
RETURNING id, school_id, classroom_id, name, encrypted_rtsp_url, r2_live_path, r2_recording_path, default_quality, status, last_segment_at, created_at, updated_at
`

type UpdateCameraParams struct {
	Name             pgtype.Text `json:"name"`
	ClassroomID      pgtype.UUID `json:"classroom_id"`
	EncryptedRtspUrl pgtype.Text `json:"encrypted_rtsp_url"`
	R2LivePath       pgtype.Text `json:"r2_live_path"`
	R2RecordingPath  pgtype.Text `json:"r2_recording_path"`
	DefaultQuality   pgtype.Text `json:"default_quality"`
	Status           pgtype.Text `json:"status"`
	ID               uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateCamera(ctx context.Context, arg UpdateCameraParams) (Camera, error) {
	row := q.db.QueryRow(ctx, updateCamera,
		arg.Name,
		arg.ClassroomID,
		arg.EncryptedRtspUrl,
		arg.R2LivePath,
		arg.R2RecordingPath,
		arg.DefaultQuality,
		arg.Status,
		arg.ID,
	)
	var i Camera
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.ClassroomID,
		&i.Name,
		&i.EncryptedRtspUrl,
		&i.R2LivePath,
		&i.R2RecordingPath,
		&i.DefaultQuality,
		&i.Status,
		&i.LastSegmentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCameraLastSegmentAt = `-- name: UpdateCameraLastSegmentAt :exec
UPDATE cameras
SET last_segment_at = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateCameraLastSegmentAtParams struct {
	ID            uuid.UUID          `json:"id"`
	LastSegmentAt pgtype.Timestamptz `json:"last_segment_at"`
}

func (q *Queries) UpdateCameraLastSegmentAt(ctx context.Context, arg UpdateCameraLastSegmentAtParams) error {
	_, err := q.db.Exec(ctx, updateCameraLastSegmentAt, arg.ID, arg.LastSegmentAt)
	return err
}
