// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: children.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignParentToChild = `-- name: AssignParentToChild :one
INSERT INTO parent_children (
    parent_id,
    child_id,
    relationship
) VALUES (
    $1, $2, $3
)
ON CONFLICT (parent_id, child_id) DO UPDATE
SET relationship = EXCLUDED.relationship
RETURNING parent_id, child_id, relationship, created_at
`

type AssignParentToChildParams struct {
	ParentID     uuid.UUID   `json:"parent_id"`
	ChildID      uuid.UUID   `json:"child_id"`
	Relationship pgtype.Text `json:"relationship"`
}

func (q *Queries) AssignParentToChild(ctx context.Context, arg AssignParentToChildParams) (ParentChild, error) {
	row := q.db.QueryRow(ctx, assignParentToChild, arg.ParentID, arg.ChildID, arg.Relationship)
	var i ParentChild
	err := row.Scan(
		&i.ParentID,
		&i.ChildID,
		&i.Relationship,
		&i.CreatedAt,
	)
	return i, err
}

const childBelongsToSchool = `-- name: ChildBelongsToSchool :one
SELECT EXISTS (
    SELECT 1 FROM children
    WHERE id = $1 AND school_id = $2
) AS belongs
`

type ChildBelongsToSchoolParams struct {
	ID       uuid.UUID `json:"id"`
	SchoolID uuid.UUID `json:"school_id"`
}

func (q *Queries) ChildBelongsToSchool(ctx context.Context, arg ChildBelongsToSchoolParams) (bool, error) {
	row := q.db.QueryRow(ctx, childBelongsToSchool, arg.ID, arg.SchoolID)
	var belongs bool
	err := row.Scan(&belongs)
	return belongs, err
}

const createChild = `-- name: CreateChild :one
INSERT INTO children (
    id,
    school_id,
    classroom_id,
    full_name,
    status
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, school_id, classroom_id, full_name, status, created_at, updated_at
`

type CreateChildParams struct {
	ID          uuid.UUID   `json:"id"`
	SchoolID    uuid.UUID   `json:"school_id"`
	ClassroomID pgtype.UUID `json:"classroom_id"`
	FullName    string      `json:"full_name"`
	Status      string      `json:"status"`
}

func (q *Queries) CreateChild(ctx context.Context, arg CreateChildParams) (Child, error) {
	row := q.db.QueryRow(ctx, createChild,
		arg.ID,
		arg.SchoolID,
		arg.ClassroomID,
		arg.FullName,
		arg.Status,
	)
	var i Child
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.ClassroomID,
		&i.FullName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChild = `-- name: GetChild :one
SELECT id, school_id, classroom_id, full_name, status, created_at, updated_at FROM children
WHERE id = $1
`

func (q *Queries) GetChild(ctx context.Context, id uuid.UUID) (Child, error) {
	row := q.db.QueryRow(ctx, getChild, id)
	var i Child
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.ClassroomID,
		&i.FullName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChildrenBySchool = `-- name: ListChildrenBySchool :many
SELECT id, school_id, classroom_id, full_name, status, created_at, updated_at FROM children
WHERE school_id = $1
  AND ($2::uuid IS NULL OR classroom_id = $2)
ORDER BY full_name
`

type ListChildrenBySchoolParams struct {
	SchoolID    uuid.UUID   `json:"school_id"`
	ClassroomID pgtype.UUID `json:"classroom_id"`
}

func (q *Queries) ListChildrenBySchool(ctx context.Context, arg ListChildrenBySchoolParams) ([]Child, error) {
	rows, err := q.db.Query(ctx, listChildrenBySchool, arg.SchoolID, arg.ClassroomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Child{}
	for rows.Next() {
		var i Child
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.ClassroomID,
			&i.FullName,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildrenForParent = `-- name: ListChildrenForParent :many
SELECT
    c.id,
    c.full_name,
    c.status,
    c.school_id,
    c.classroom_id,
    s.name AS school_name,
    cr.name AS classroom_name
FROM children c
INNER JOIN parent_children pc ON pc.child_id = c.id
INNER JOIN schools s ON s.id = c.school_id
LEFT JOIN classrooms cr ON cr.id = c.classroom_id
WHERE pc.parent_id = $1
ORDER BY c.full_name
`

type ListChildrenForParentRow struct {
	ID            uuid.UUID   `json:"id"`
	FullName      string      `json:"full_name"`
	Status        string      `json:"status"`
	SchoolID      uuid.UUID   `json:"school_id"`
	ClassroomID   pgtype.UUID `json:"classroom_id"`
	SchoolName    string      `json:"school_name"`
	ClassroomName pgtype.Text `json:"classroom_name"`
}

func (q *Queries) ListChildrenForParent(ctx context.Context, parentID uuid.UUID) ([]ListChildrenForParentRow, error) {
	rows, err := q.db.Query(ctx, listChildrenForParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChildrenForParentRow{}
	for rows.Next() {
		var i ListChildrenForParentRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Status,
			&i.SchoolID,
			&i.ClassroomID,
			&i.SchoolName,
			&i.ClassroomName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentsForChild = `-- name: ListParentsForChild :many
SELECT u.id, u.full_name, u.email, u.phone, u.role, u.status, pc.relationship, pc.created_at AS linked_at
FROM parent_children pc
INNER JOIN users u ON u.id = pc.parent_id
WHERE pc.child_id = $1
ORDER BY u.full_name
`

type ListParentsForChildRow struct {
	ID           uuid.UUID          `json:"id"`
	FullName     string             `json:"full_name"`
	Email        pgtype.Text        `json:"email"`
	Phone        pgtype.Text        `json:"phone"`
	Role         string             `json:"role"`
	Status       string             `json:"status"`
	Relationship pgtype.Text        `json:"relationship"`
	LinkedAt     pgtype.Timestamptz `json:"linked_at"`
}

func (q *Queries) ListParentsForChild(ctx context.Context, childID uuid.UUID) ([]ListParentsForChildRow, error) {
	rows, err := q.db.Query(ctx, listParentsForChild, childID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParentsForChildRow{}
	for rows.Next() {
		var i ListParentsForChildRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.Role,
			&i.Status,
			&i.Relationship,
			&i.LinkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChild = `-- name: UpdateChild :one
UPDATE children
SET
    full_name = COALESCE($1, full_name),
    classroom_id = COALESCE($2, classroom_id),
    status = COALESCE($3, status),
    updated_at = NOW()
WHERE id = $4
RETURNING id, school_id, classroom_id, full_name, status, created_at, updated_at
`

type UpdateChildParams struct {
	FullName    pgtype.Text `json:"full_name"`
	ClassroomID pgtype.UUID `json:"classroom_id"`
	Status      pgtype.Text `json:"status"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateChild(ctx context.Context, arg UpdateChildParams) (Child, error) {
	row := q.db.QueryRow(ctx, updateChild,
		arg.FullName,
		arg.ClassroomID,
		arg.Status,
		arg.ID,
	)
	var i Child
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.ClassroomID,
		&i.FullName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
