// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classrooms.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const classroomBelongsToSchool = `-- name: ClassroomBelongsToSchool :one
SELECT EXISTS (
    SELECT 1 FROM classrooms
    WHERE id = $1 AND school_id = $2
) AS belongs
`

type ClassroomBelongsToSchoolParams struct {
	ID       uuid.UUID `json:"id"`
	SchoolID uuid.UUID `json:"school_id"`
}

func (q *Queries) ClassroomBelongsToSchool(ctx context.Context, arg ClassroomBelongsToSchoolParams) (bool, error) {
	row := q.db.QueryRow(ctx, classroomBelongsToSchool, arg.ID, arg.SchoolID)
	var belongs bool
	err := row.Scan(&belongs)
	return belongs, err
}

const createClassroom = `-- name: CreateClassroom :one
INSERT INTO classrooms (
    id,
    school_id,
    name,
    age_group,
    status
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, school_id, name, age_group, status, created_at, updated_at
`

type CreateClassroomParams struct {
	ID       uuid.UUID   `json:"id"`
	SchoolID uuid.UUID   `json:"school_id"`
	Name     string      `json:"name"`
	AgeGroup pgtype.Text `json:"age_group"`
	Status   string      `json:"status"`
}

func (q *Queries) CreateClassroom(ctx context.Context, arg CreateClassroomParams) (Classroom, error) {
	row := q.db.QueryRow(ctx, createClassroom,
		arg.ID,
		arg.SchoolID,
		arg.Name,
		arg.AgeGroup,
		arg.Status,
	)
	var i Classroom
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.AgeGroup,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClassroom = `-- name: GetClassroom :one
SELECT id, school_id, name, age_group, status, created_at, updated_at FROM classrooms
WHERE id = $1
`

func (q *Queries) GetClassroom(ctx context.Context, id uuid.UUID) (Classroom, error) {
	row := q.db.QueryRow(ctx, getClassroom, id)
	var i Classroom
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.AgeGroup,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClassroomsBySchool = `-- name: ListClassroomsBySchool :many
SELECT id, school_id, name, age_group, status, created_at, updated_at FROM classrooms
WHERE school_id = $1
ORDER BY name
`

func (q *Queries) ListClassroomsBySchool(ctx context.Context, schoolID uuid.UUID) ([]Classroom, error) {
	rows, err := q.db.Query(ctx, listClassroomsBySchool, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Classroom{}
	for rows.Next() {
		var i Classroom
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Name,
			&i.AgeGroup,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClassroom = `-- name: UpdateClassroom :one
UPDATE classrooms
SET
    name = COALESCE($1, name),
    age_group = COALESCE($2, age_group),
    status = COALESCE($3, status),
    updated_at = NOW()
WHERE id = $4
RETURNING id, school_id, name, age_group, status, created_at, updated_at
`

type UpdateClassroomParams struct {
	Name     pgtype.Text `json:"name"`
	AgeGroup pgtype.Text `json:"age_group"`
	Status   pgtype.Text `json:"status"`
	ID       uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateClassroom(ctx context.Context, arg UpdateClassroomParams) (Classroom, error) {
	row := q.db.QueryRow(ctx, updateClassroom,
		arg.Name,
		arg.AgeGroup,
		arg.Status,
		arg.ID,
	)
	var i Classroom
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Name,
		&i.AgeGroup,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
