// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: health.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSchools = `-- name: CountActiveSchools :one
SELECT COUNT(*)::bigint FROM schools WHERE status = 'ACTIVE'
`

func (q *Queries) CountActiveSchools(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSchools)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countAlertsByStatus = `-- name: CountAlertsByStatus :one
SELECT COUNT(*)::bigint
FROM alerts
WHERE status = $1
  AND ($2::uuid[] IS NULL OR school_id = ANY($2::uuid[]))
`

type CountAlertsByStatusParams struct {
	Status    string      `json:"status"`
	SchoolIds []uuid.UUID `json:"school_ids"`
}

func (q *Queries) CountAlertsByStatus(ctx context.Context, arg CountAlertsByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAlertsByStatus, arg.Status, arg.SchoolIds)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countAlertsByStatusAndSeverity = `-- name: CountAlertsByStatusAndSeverity :one
SELECT COUNT(*)::bigint
FROM alerts
WHERE status = $1
  AND severity = $2
  AND ($3::uuid[] IS NULL OR school_id = ANY($3::uuid[]))
`

type CountAlertsByStatusAndSeverityParams struct {
	Status    string      `json:"status"`
	Severity  string      `json:"severity"`
	SchoolIds []uuid.UUID `json:"school_ids"`
}

func (q *Queries) CountAlertsByStatusAndSeverity(ctx context.Context, arg CountAlertsByStatusAndSeverityParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAlertsByStatusAndSeverity, arg.Status, arg.Severity, arg.SchoolIds)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countAlertsFiltered = `-- name: CountAlertsFiltered :one
SELECT COUNT(*)::bigint AS total
FROM alerts
WHERE ($1::uuid[] IS NULL OR school_id = ANY($1::uuid[]))
  AND ($2::text IS NULL OR status = $2)
  AND ($3::text IS NULL OR severity = $3)
  AND ($4::text IS NULL OR alert_type = $4)
  AND ($5::uuid IS NULL OR school_id = $5)
  AND ($6::uuid IS NULL OR camera_id = $6)
`

type CountAlertsFilteredParams struct {
	SchoolIds []uuid.UUID `json:"school_ids"`
	Status    pgtype.Text `json:"status"`
	Severity  pgtype.Text `json:"severity"`
	AlertType pgtype.Text `json:"alert_type"`
	SchoolID  pgtype.UUID `json:"school_id"`
	CameraID  pgtype.UUID `json:"camera_id"`
}

func (q *Queries) CountAlertsFiltered(ctx context.Context, arg CountAlertsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAlertsFiltered,
		arg.SchoolIds,
		arg.Status,
		arg.Severity,
		arg.AlertType,
		arg.SchoolID,
		arg.CameraID,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countCamerasByStatus = `-- name: CountCamerasByStatus :one
SELECT COUNT(*)::bigint
FROM cameras cam
INNER JOIN schools s ON s.id = cam.school_id AND s.status = 'ACTIVE'
WHERE cam.status = $1
`

func (q *Queries) CountCamerasByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countCamerasByStatus, status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countRecentCameraHealthEvents = `-- name: CountRecentCameraHealthEvents :one
SELECT COUNT(*)::bigint AS event_count
FROM camera_health_events
WHERE camera_id = $1
  AND event_type = $2
  AND created_at >= NOW() - ($3::int * INTERVAL '1 minute')
`

type CountRecentCameraHealthEventsParams struct {
	CameraID  uuid.UUID `json:"camera_id"`
	EventType string    `json:"event_type"`
	Column3   int32     `json:"column_3"`
}

func (q *Queries) CountRecentCameraHealthEvents(ctx context.Context, arg CountRecentCameraHealthEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentCameraHealthEvents, arg.CameraID, arg.EventType, arg.Column3)
	var event_count int64
	err := row.Scan(&event_count)
	return event_count, err
}

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (
    id,
    school_id,
    camera_id,
    alert_type,
    severity,
    status,
    title,
    message,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, 'OPEN', $6, $7, $8
)
RETURNING id, school_id, camera_id, alert_type, severity, status, title, message, metadata, opened_at, resolved_at, created_at, updated_at
`

type CreateAlertParams struct {
	ID        uuid.UUID   `json:"id"`
	SchoolID  pgtype.UUID `json:"school_id"`
	CameraID  pgtype.UUID `json:"camera_id"`
	AlertType string      `json:"alert_type"`
	Severity  string      `json:"severity"`
	Title     string      `json:"title"`
	Message   pgtype.Text `json:"message"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, createAlert,
		arg.ID,
		arg.SchoolID,
		arg.CameraID,
		arg.AlertType,
		arg.Severity,
		arg.Title,
		arg.Message,
		arg.Metadata,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.CameraID,
		&i.AlertType,
		&i.Severity,
		&i.Status,
		&i.Title,
		&i.Message,
		&i.Metadata,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlertByID = `-- name: GetAlertByID :one
SELECT id, school_id, camera_id, alert_type, severity, status, title, message, metadata, opened_at, resolved_at, created_at, updated_at
FROM alerts
WHERE id = $1
`

func (q *Queries) GetAlertByID(ctx context.Context, id uuid.UUID) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlertByID, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.CameraID,
		&i.AlertType,
		&i.Severity,
		&i.Status,
		&i.Title,
		&i.Message,
		&i.Metadata,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestCameraHealthEvent = `-- name: GetLatestCameraHealthEvent :one
SELECT id, camera_id, school_id, event_type, severity, message, metadata, created_at
FROM camera_health_events
WHERE camera_id = $1
  AND event_type = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestCameraHealthEventParams struct {
	CameraID  uuid.UUID `json:"camera_id"`
	EventType string    `json:"event_type"`
}

func (q *Queries) GetLatestCameraHealthEvent(ctx context.Context, arg GetLatestCameraHealthEventParams) (CameraHealthEvent, error) {
	row := q.db.QueryRow(ctx, getLatestCameraHealthEvent, arg.CameraID, arg.EventType)
	var i CameraHealthEvent
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.SchoolID,
		&i.EventType,
		&i.Severity,
		&i.Message,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestRecordingSegmentStartForCamera = `-- name: GetLatestRecordingSegmentStartForCamera :one
SELECT MAX(start_time)::timestamptz AS latest_start
FROM recording_segments
WHERE camera_id = $1
  AND expires_at > NOW()
`

func (q *Queries) GetLatestRecordingSegmentStartForCamera(ctx context.Context, cameraID uuid.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLatestRecordingSegmentStartForCamera, cameraID)
	var latest_start pgtype.Timestamptz
	err := row.Scan(&latest_start)
	return latest_start, err
}

const getLatestWorkerHeartbeatByType = `-- name: GetLatestWorkerHeartbeatByType :one
SELECT id, worker_name, worker_type, status, metadata, last_seen_at, created_at
FROM worker_heartbeats
WHERE worker_type = $1
ORDER BY last_seen_at DESC
LIMIT 1
`

func (q *Queries) GetLatestWorkerHeartbeatByType(ctx context.Context, workerType string) (WorkerHeartbeat, error) {
	row := q.db.QueryRow(ctx, getLatestWorkerHeartbeatByType, workerType)
	var i WorkerHeartbeat
	err := row.Scan(
		&i.ID,
		&i.WorkerName,
		&i.WorkerType,
		&i.Status,
		&i.Metadata,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOpenAlertByTypeAndCamera = `-- name: GetOpenAlertByTypeAndCamera :one
SELECT id, school_id, camera_id, alert_type, severity, status, title, message, metadata, opened_at, resolved_at, created_at, updated_at
FROM alerts
WHERE alert_type = $1
  AND camera_id = $2
  AND status IN ('OPEN', 'ACKNOWLEDGED')
LIMIT 1
`

type GetOpenAlertByTypeAndCameraParams struct {
	AlertType string      `json:"alert_type"`
	CameraID  pgtype.UUID `json:"camera_id"`
}

func (q *Queries) GetOpenAlertByTypeAndCamera(ctx context.Context, arg GetOpenAlertByTypeAndCameraParams) (Alert, error) {
	row := q.db.QueryRow(ctx, getOpenAlertByTypeAndCamera, arg.AlertType, arg.CameraID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.CameraID,
		&i.AlertType,
		&i.Severity,
		&i.Status,
		&i.Title,
		&i.Message,
		&i.Metadata,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenAlertByTypeAndSchool = `-- name: GetOpenAlertByTypeAndSchool :one
SELECT id, school_id, camera_id, alert_type, severity, status, title, message, metadata, opened_at, resolved_at, created_at, updated_at
FROM alerts
WHERE alert_type = $1
  AND school_id = $2
  AND camera_id IS NULL
  AND status IN ('OPEN', 'ACKNOWLEDGED')
LIMIT 1
`

type GetOpenAlertByTypeAndSchoolParams struct {
	AlertType string      `json:"alert_type"`
	SchoolID  pgtype.UUID `json:"school_id"`
}

func (q *Queries) GetOpenAlertByTypeAndSchool(ctx context.Context, arg GetOpenAlertByTypeAndSchoolParams) (Alert, error) {
	row := q.db.QueryRow(ctx, getOpenAlertByTypeAndSchool, arg.AlertType, arg.SchoolID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.CameraID,
		&i.AlertType,
		&i.Severity,
		&i.Status,
		&i.Title,
		&i.Message,
		&i.Metadata,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenAlertByTypeGlobal = `-- name: GetOpenAlertByTypeGlobal :one
SELECT id, school_id, camera_id, alert_type, severity, status, title, message, metadata, opened_at, resolved_at, created_at, updated_at
FROM alerts
WHERE alert_type = $1
  AND school_id IS NULL
  AND camera_id IS NULL
  AND status IN ('OPEN', 'ACKNOWLEDGED')
LIMIT 1
`

func (q *Queries) GetOpenAlertByTypeGlobal(ctx context.Context, alertType string) (Alert, error) {
	row := q.db.QueryRow(ctx, getOpenAlertByTypeGlobal, alertType)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.CameraID,
		&i.AlertType,
		&i.Severity,
		&i.Status,
		&i.Title,
		&i.Message,
		&i.Metadata,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecentCameraHealthEvents = `-- name: GetRecentCameraHealthEvents :many
SELECT id, camera_id, school_id, event_type, severity, message, metadata, created_at
FROM camera_health_events
WHERE camera_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetRecentCameraHealthEventsParams struct {
	CameraID uuid.UUID `json:"camera_id"`
	Limit    int32     `json:"limit"`
}

func (q *Queries) GetRecentCameraHealthEvents(ctx context.Context, arg GetRecentCameraHealthEventsParams) ([]CameraHealthEvent, error) {
	rows, err := q.db.Query(ctx, getRecentCameraHealthEvents, arg.CameraID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CameraHealthEvent{}
	for rows.Next() {
		var i CameraHealthEvent
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.SchoolID,
			&i.EventType,
			&i.Severity,
			&i.Message,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveCamerasForHealth = `-- name: ListActiveCamerasForHealth :many
SELECT
    cam.id,
    cam.school_id,
    cam.name,
    cam.r2_live_path,
    cam.default_quality,
    cam.status,
    cam.last_segment_at,
    cam.updated_at
FROM cameras cam
INNER JOIN schools s ON s.id = cam.school_id AND s.status = 'ACTIVE'
INNER JOIN classrooms cr ON cr.id = cam.classroom_id AND cr.status = 'ACTIVE'
WHERE cam.status IN ('ACTIVE', 'OFFLINE')
ORDER BY cam.school_id, cam.name
`

type ListActiveCamerasForHealthRow struct {
	ID             uuid.UUID          `json:"id"`
	SchoolID       uuid.UUID          `json:"school_id"`
	Name           string             `json:"name"`
	R2LivePath     string             `json:"r2_live_path"`
	DefaultQuality string             `json:"default_quality"`
	Status         string             `json:"status"`
	LastSegmentAt  pgtype.Timestamptz `json:"last_segment_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActiveCamerasForHealth(ctx context.Context) ([]ListActiveCamerasForHealthRow, error) {
	rows, err := q.db.Query(ctx, listActiveCamerasForHealth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveCamerasForHealthRow{}
	for rows.Next() {
		var i ListActiveCamerasForHealthRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.Name,
			&i.R2LivePath,
			&i.DefaultQuality,
			&i.Status,
			&i.LastSegmentAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlerts = `-- name: ListAlerts :many
SELECT id, school_id, camera_id, alert_type, severity, status, title, message, metadata, opened_at, resolved_at, created_at, updated_at
FROM alerts
WHERE ($1::uuid[] IS NULL OR school_id = ANY($1::uuid[]))
  AND ($2::text IS NULL OR status = $2)
  AND ($3::text IS NULL OR severity = $3)
  AND ($4::text IS NULL OR alert_type = $4)
  AND ($5::uuid IS NULL OR school_id = $5)
  AND ($6::uuid IS NULL OR camera_id = $6)
ORDER BY opened_at DESC
LIMIT $8 OFFSET $7
`

type ListAlertsParams struct {
	SchoolIds []uuid.UUID `json:"school_ids"`
	Status    pgtype.Text `json:"status"`
	Severity  pgtype.Text `json:"severity"`
	AlertType pgtype.Text `json:"alert_type"`
	SchoolID  pgtype.UUID `json:"school_id"`
	CameraID  pgtype.UUID `json:"camera_id"`
	RowOffset int32       `json:"row_offset"`
	RowLimit  int32       `json:"row_limit"`
}

func (q *Queries) ListAlerts(ctx context.Context, arg ListAlertsParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlerts,
		arg.SchoolIds,
		arg.Status,
		arg.Severity,
		arg.AlertType,
		arg.SchoolID,
		arg.CameraID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.CameraID,
			&i.AlertType,
			&i.Severity,
			&i.Status,
			&i.Title,
			&i.Message,
			&i.Metadata,
			&i.OpenedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCameraHealthEventsSince = `-- name: ListCameraHealthEventsSince :many
SELECT id, camera_id, school_id, event_type, severity, message, metadata, created_at
FROM camera_health_events
WHERE camera_id = $1
  AND created_at >= $2
ORDER BY created_at DESC
LIMIT $3
`

type ListCameraHealthEventsSinceParams struct {
	CameraID  uuid.UUID          `json:"camera_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListCameraHealthEventsSince(ctx context.Context, arg ListCameraHealthEventsSinceParams) ([]CameraHealthEvent, error) {
	rows, err := q.db.Query(ctx, listCameraHealthEventsSince, arg.CameraID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CameraHealthEvent{}
	for rows.Next() {
		var i CameraHealthEvent
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.SchoolID,
			&i.EventType,
			&i.Severity,
			&i.Message,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenAlertsForCamera = `-- name: ListOpenAlertsForCamera :many
SELECT id, school_id, camera_id, alert_type, severity, status, title, message, metadata, opened_at, resolved_at, created_at, updated_at
FROM alerts
WHERE camera_id = $1
  AND status IN ('OPEN', 'ACKNOWLEDGED')
ORDER BY opened_at DESC
`

func (q *Queries) ListOpenAlertsForCamera(ctx context.Context, cameraID pgtype.UUID) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listOpenAlertsForCamera, cameraID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.CameraID,
			&i.AlertType,
			&i.Severity,
			&i.Status,
			&i.Title,
			&i.Message,
			&i.Metadata,
			&i.OpenedAt,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchoolIDsForUser = `-- name: ListSchoolIDsForUser :many
SELECT school_id
FROM school_admins
WHERE user_id = $1
`

func (q *Queries) ListSchoolIDsForUser(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSchoolIDsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var school_id uuid.UUID
		if err := rows.Scan(&school_id); err != nil {
			return nil, err
		}
		items = append(items, school_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAlert = `-- name: ResolveAlert :one
UPDATE alerts
SET status = 'RESOLVED',
    resolved_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, school_id, camera_id, alert_type, severity, status, title, message, metadata, opened_at, resolved_at, created_at, updated_at
`

func (q *Queries) ResolveAlert(ctx context.Context, id uuid.UUID) (Alert, error) {
	row := q.db.QueryRow(ctx, resolveAlert, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.CameraID,
		&i.AlertType,
		&i.Severity,
		&i.Status,
		&i.Title,
		&i.Message,
		&i.Metadata,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchAlertMetadata = `-- name: TouchAlertMetadata :one
UPDATE alerts
SET metadata = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, school_id, camera_id, alert_type, severity, status, title, message, metadata, opened_at, resolved_at, created_at, updated_at
`

type TouchAlertMetadataParams struct {
	ID       uuid.UUID `json:"id"`
	Metadata []byte    `json:"metadata"`
}

func (q *Queries) TouchAlertMetadata(ctx context.Context, arg TouchAlertMetadataParams) (Alert, error) {
	row := q.db.QueryRow(ctx, touchAlertMetadata, arg.ID, arg.Metadata)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.CameraID,
		&i.AlertType,
		&i.Severity,
		&i.Status,
		&i.Title,
		&i.Message,
		&i.Metadata,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAlertStatus = `-- name: UpdateAlertStatus :one
UPDATE alerts
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, school_id, camera_id, alert_type, severity, status, title, message, metadata, opened_at, resolved_at, created_at, updated_at
`

type UpdateAlertStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateAlertStatus(ctx context.Context, arg UpdateAlertStatusParams) (Alert, error) {
	row := q.db.QueryRow(ctx, updateAlertStatus, arg.ID, arg.Status)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.CameraID,
		&i.AlertType,
		&i.Severity,
		&i.Status,
		&i.Title,
		&i.Message,
		&i.Metadata,
		&i.OpenedAt,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
