// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID         uuid.UUID          `json:"id"`
	SchoolID   pgtype.UUID        `json:"school_id"`
	CameraID   pgtype.UUID        `json:"camera_id"`
	AlertType  string             `json:"alert_type"`
	Severity   string             `json:"severity"`
	Status     string             `json:"status"`
	Title      string             `json:"title"`
	Message    pgtype.Text        `json:"message"`
	Metadata   []byte             `json:"metadata"`
	OpenedAt   pgtype.Timestamptz `json:"opened_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type AlertDelivery struct {
	ID           uuid.UUID          `json:"id"`
	AlertID      uuid.UUID          `json:"alert_id"`
	Channel      string             `json:"channel"`
	Recipient    string             `json:"recipient"`
	DeliveryKind string             `json:"delivery_kind"`
	Status       string             `json:"status"`
	Attempts     int32              `json:"attempts"`
	LastError    pgtype.Text        `json:"last_error"`
	DeliveredAt  pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID          uuid.UUID          `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	SchoolID    pgtype.UUID        `json:"school_id"`
	ClassroomID pgtype.UUID        `json:"classroom_id"`
	CameraID    pgtype.UUID        `json:"camera_id"`
	ChildID     pgtype.UUID        `json:"child_id"`
	DeviceID    pgtype.UUID        `json:"device_id"`
	Action      string             `json:"action"`
	IpAddress   pgtype.Text        `json:"ip_address"`
	UserAgent   pgtype.Text        `json:"user_agent"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Camera struct {
	ID               uuid.UUID          `json:"id"`
	SchoolID         uuid.UUID          `json:"school_id"`
	ClassroomID      pgtype.UUID        `json:"classroom_id"`
	Name             string             `json:"name"`
	EncryptedRtspUrl pgtype.Text        `json:"encrypted_rtsp_url"`
	R2LivePath       string             `json:"r2_live_path"`
	R2RecordingPath  pgtype.Text        `json:"r2_recording_path"`
	DefaultQuality   string             `json:"default_quality"`
	Status           string             `json:"status"`
	LastSegmentAt    pgtype.Timestamptz `json:"last_segment_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type CameraHealthEvent struct {
	ID        uuid.UUID          `json:"id"`
	CameraID  uuid.UUID          `json:"camera_id"`
	SchoolID  uuid.UUID          `json:"school_id"`
	EventType string             `json:"event_type"`
	Severity  string             `json:"severity"`
	Message   pgtype.Text        `json:"message"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CameraStreamState struct {
	CameraID     uuid.UUID          `json:"camera_id"`
	DesiredState string             `json:"desired_state"`
	Reason       pgtype.Text        `json:"reason"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Child struct {
	ID          uuid.UUID          `json:"id"`
	SchoolID    uuid.UUID          `json:"school_id"`
	ClassroomID pgtype.UUID        `json:"classroom_id"`
	FullName    string             `json:"full_name"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Classroom struct {
	ID        uuid.UUID          `json:"id"`
	SchoolID  uuid.UUID          `json:"school_id"`
	Name      string             `json:"name"`
	AgeGroup  pgtype.Text        `json:"age_group"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Device struct {
	ID                      uuid.UUID          `json:"id"`
	UserID                  uuid.UUID          `json:"user_id"`
	DeviceName              pgtype.Text        `json:"device_name"`
	DeviceFingerprint       string             `json:"device_fingerprint"`
	Status                  string             `json:"status"`
	LastSeenAt              pgtype.Timestamptz `json:"last_seen_at"`
	FcmToken                pgtype.Text        `json:"fcm_token"`
	PushPlatform            pgtype.Text        `json:"push_platform"`
	NotificationsEnabled    bool               `json:"notifications_enabled"`
	NotificationPreferences json.RawMessage    `json:"notification_preferences"`
	FcmTokenUpdatedAt       pgtype.Timestamptz `json:"fcm_token_updated_at"`
	AppVersion              pgtype.Text        `json:"app_version"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

type Invoice struct {
	ID             uuid.UUID          `json:"id"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	SchoolID       pgtype.UUID        `json:"school_id"`
	SubscriptionID pgtype.UUID        `json:"subscription_id"`
	InvoiceNumber  string             `json:"invoice_number"`
	AmountCents    int64              `json:"amount_cents"`
	Currency       string             `json:"currency"`
	Status         string             `json:"status"`
	DueDate        pgtype.Date        `json:"due_date"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ParentChild struct {
	ParentID     uuid.UUID          `json:"parent_id"`
	ChildID      uuid.UUID          `json:"child_id"`
	Relationship pgtype.Text        `json:"relationship"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID             uuid.UUID          `json:"id"`
	ParentID       pgtype.UUID        `json:"parent_id"`
	SchoolID       pgtype.UUID        `json:"school_id"`
	SubscriptionID pgtype.UUID        `json:"subscription_id"`
	AmountCents    int64              `json:"amount_cents"`
	Currency       string             `json:"currency"`
	Method         string             `json:"method"`
	Status         string             `json:"status"`
	Reference      pgtype.Text        `json:"reference"`
	ProofUrl       pgtype.Text        `json:"proof_url"`
	Notes          pgtype.Text        `json:"notes"`
	ApprovedBy     pgtype.UUID        `json:"approved_by"`
	ApprovedAt     pgtype.Timestamptz `json:"approved_at"`
	RejectedBy     pgtype.UUID        `json:"rejected_by"`
	RejectedAt     pgtype.Timestamptz `json:"rejected_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type RecordingSegment struct {
	ID              uuid.UUID          `json:"id"`
	CameraID        uuid.UUID          `json:"camera_id"`
	SchoolID        uuid.UUID          `json:"school_id"`
	SegmentPath     string             `json:"segment_path"`
	PlaylistPath    pgtype.Text        `json:"playlist_path"`
	Quality         string             `json:"quality"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	DurationSeconds int32              `json:"duration_seconds"`
	SizeBytes       int64              `json:"size_bytes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

type RefreshToken struct {
	ID                  uuid.UUID          `json:"id"`
	UserID              uuid.UUID          `json:"user_id"`
	TokenHash           string             `json:"token_hash"`
	DeviceID            pgtype.UUID        `json:"device_id"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	RevokedAt           pgtype.Timestamptz `json:"revoked_at"`
	ReplacedByTokenHash pgtype.Text        `json:"replaced_by_token_hash"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type School struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Address   pgtype.Text        `json:"address"`
	Phone     pgtype.Text        `json:"phone"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type SchoolAdmin struct {
	SchoolID  uuid.UUID          `json:"school_id"`
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SchoolRevenueShare struct {
	ID         uuid.UUID          `json:"id"`
	SchoolID   uuid.UUID          `json:"school_id"`
	Percentage pgtype.Numeric     `json:"percentage"`
	ActiveFrom pgtype.Date        `json:"active_from"`
	ActiveTo   pgtype.Date        `json:"active_to"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type StorageUsage struct {
	ID               uuid.UUID          `json:"id"`
	SchoolID         uuid.UUID          `json:"school_id"`
	Date             pgtype.Date        `json:"date"`
	TotalBytes       int64              `json:"total_bytes"`
	SegmentCount     int64              `json:"segment_count"`
	EstimatedCostUsd pgtype.Numeric     `json:"estimated_cost_usd"`
	Metadata         []byte             `json:"metadata"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Subscription struct {
	ID        uuid.UUID          `json:"id"`
	ParentID  uuid.UUID          `json:"parent_id"`
	SchoolID  uuid.UUID          `json:"school_id"`
	Status    string             `json:"status"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	EndsAt    pgtype.Timestamptz `json:"ends_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                  uuid.UUID          `json:"id"`
	FullName            string             `json:"full_name"`
	Phone               pgtype.Text        `json:"phone"`
	Email               pgtype.Text        `json:"email"`
	PasswordHash        pgtype.Text        `json:"password_hash"`
	Role                string             `json:"role"`
	Status              string             `json:"status"`
	ForcePasswordChange bool               `json:"force_password_change"`
	PasswordChangedAt   pgtype.Timestamptz `json:"password_changed_at"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	CreatedByUserID     pgtype.UUID        `json:"created_by_user_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type WorkerHeartbeat struct {
	ID         uuid.UUID          `json:"id"`
	WorkerName string             `json:"worker_name"`
	WorkerType string             `json:"worker_type"`
	Status     string             `json:"status"`
	Metadata   []byte             `json:"metadata"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
