// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitoring.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditActionsScoped = `-- name: CountAuditActionsScoped :one
SELECT COUNT(*)::bigint AS total
FROM audit_logs al
WHERE al.action = ANY($3::text[])
  AND al.created_at >= $1
  AND al.created_at < $2
  AND (
    $4::uuid[] IS NULL
    OR al.school_id = ANY($4::uuid[])
    OR al.user_id IN (
        SELECT DISTINCT pc.parent_id
        FROM parent_children pc
        INNER JOIN children ch ON ch.id = pc.child_id
        WHERE ch.school_id = ANY($4::uuid[])
    )
  )
`

type CountAuditActionsScopedParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	Actions     []string           `json:"actions"`
	SchoolIds   []uuid.UUID        `json:"school_ids"`
}

func (q *Queries) CountAuditActionsScoped(ctx context.Context, arg CountAuditActionsScopedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditActionsScoped,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Actions,
		arg.SchoolIds,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countAuditLogsFiltered = `-- name: CountAuditLogsFiltered :one
SELECT COUNT(*)::bigint AS total
FROM audit_logs al
WHERE ($1::uuid[] IS NULL OR al.school_id = ANY($1::uuid[]))
  AND ($2::uuid IS NULL OR al.school_id = $2)
  AND ($3::uuid IS NULL OR al.user_id = $3)
  AND ($4::uuid IS NULL OR al.camera_id = $4)
  AND ($5::text IS NULL OR al.action = $5)
  AND ($6::timestamptz IS NULL OR al.created_at >= $6)
  AND ($7::timestamptz IS NULL OR al.created_at < $7)
`

type CountAuditLogsFilteredParams struct {
	SchoolIds []uuid.UUID        `json:"school_ids"`
	SchoolID  pgtype.UUID        `json:"school_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CameraID  pgtype.UUID        `json:"camera_id"`
	Action    pgtype.Text        `json:"action"`
	DateFrom  pgtype.Timestamptz `json:"date_from"`
	DateTo    pgtype.Timestamptz `json:"date_to"`
}

func (q *Queries) CountAuditLogsFiltered(ctx context.Context, arg CountAuditLogsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogsFiltered,
		arg.SchoolIds,
		arg.SchoolID,
		arg.UserID,
		arg.CameraID,
		arg.Action,
		arg.DateFrom,
		arg.DateTo,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countCamerasByStatusScoped = `-- name: CountCamerasByStatusScoped :one
SELECT COUNT(*)::bigint AS total
FROM cameras cam
WHERE cam.status = $1
  AND ($2::uuid[] IS NULL OR cam.school_id = ANY($2::uuid[]))
`

type CountCamerasByStatusScopedParams struct {
	Status    string      `json:"status"`
	SchoolIds []uuid.UUID `json:"school_ids"`
}

func (q *Queries) CountCamerasByStatusScoped(ctx context.Context, arg CountCamerasByStatusScopedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCamerasByStatusScoped, arg.Status, arg.SchoolIds)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countCamerasScoped = `-- name: CountCamerasScoped :one
SELECT COUNT(*)::bigint AS total
FROM cameras cam
WHERE ($1::uuid[] IS NULL OR cam.school_id = ANY($1::uuid[]))
`

func (q *Queries) CountCamerasScoped(ctx context.Context, schoolIds []uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCamerasScoped, schoolIds)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countChildrenScoped = `-- name: CountChildrenScoped :one
SELECT COUNT(*)::bigint AS total
FROM children ch
WHERE ($1::uuid[] IS NULL OR ch.school_id = ANY($1::uuid[]))
`

func (q *Queries) CountChildrenScoped(ctx context.Context, schoolIds []uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChildrenScoped, schoolIds)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countHealthyCamerasScoped = `-- name: CountHealthyCamerasScoped :one
SELECT COUNT(*)::bigint AS total
FROM cameras cam
WHERE cam.status = 'ACTIVE'
  AND cam.last_segment_at IS NOT NULL
  AND cam.last_segment_at > NOW() - ($1::int * INTERVAL '1 second')
  AND ($2::uuid[] IS NULL OR cam.school_id = ANY($2::uuid[]))
`

type CountHealthyCamerasScopedParams struct {
	MaxSegmentAgeSeconds int32       `json:"max_segment_age_seconds"`
	SchoolIds            []uuid.UUID `json:"school_ids"`
}

func (q *Queries) CountHealthyCamerasScoped(ctx context.Context, arg CountHealthyCamerasScopedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countHealthyCamerasScoped, arg.MaxSegmentAgeSeconds, arg.SchoolIds)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countOpenAlertsBySeverityScoped = `-- name: CountOpenAlertsBySeverityScoped :one
SELECT COUNT(*)::bigint AS total
FROM alerts a
WHERE a.status IN ('OPEN', 'ACKNOWLEDGED')
  AND a.severity = $1
  AND ($2::uuid[] IS NULL OR a.school_id = ANY($2::uuid[]))
`

type CountOpenAlertsBySeverityScopedParams struct {
	Severity  string      `json:"severity"`
	SchoolIds []uuid.UUID `json:"school_ids"`
}

func (q *Queries) CountOpenAlertsBySeverityScoped(ctx context.Context, arg CountOpenAlertsBySeverityScopedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenAlertsBySeverityScoped, arg.Severity, arg.SchoolIds)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countOpenAlertsScoped = `-- name: CountOpenAlertsScoped :one
SELECT COUNT(*)::bigint AS total
FROM alerts a
WHERE a.status IN ('OPEN', 'ACKNOWLEDGED')
  AND ($1::uuid[] IS NULL OR a.school_id = ANY($1::uuid[]))
`

func (q *Queries) CountOpenAlertsScoped(ctx context.Context, schoolIds []uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenAlertsScoped, schoolIds)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countParentsByStatusScoped = `-- name: CountParentsByStatusScoped :one
SELECT COUNT(DISTINCT u.id)::bigint AS total
FROM users u
WHERE u.role = 'PARENT'
  AND u.status = $1
  AND (
    $2::uuid[] IS NULL
    OR EXISTS (
        SELECT 1
        FROM parent_children pc
        INNER JOIN children ch ON ch.id = pc.child_id
        WHERE pc.parent_id = u.id
          AND ch.school_id = ANY($2::uuid[])
    )
    OR EXISTS (
        SELECT 1
        FROM subscriptions sub
        WHERE sub.parent_id = u.id
          AND sub.school_id = ANY($2::uuid[])
    )
  )
`

type CountParentsByStatusScopedParams struct {
	Status    string      `json:"status"`
	SchoolIds []uuid.UUID `json:"school_ids"`
}

func (q *Queries) CountParentsByStatusScoped(ctx context.Context, arg CountParentsByStatusScopedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countParentsByStatusScoped, arg.Status, arg.SchoolIds)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countParentsScoped = `-- name: CountParentsScoped :one
SELECT COUNT(DISTINCT u.id)::bigint AS total
FROM users u
WHERE u.role = 'PARENT'
  AND (
    $1::uuid[] IS NULL
    OR EXISTS (
        SELECT 1
        FROM parent_children pc
        INNER JOIN children ch ON ch.id = pc.child_id
        WHERE pc.parent_id = u.id
          AND ch.school_id = ANY($1::uuid[])
    )
    OR EXISTS (
        SELECT 1
        FROM subscriptions sub
        WHERE sub.parent_id = u.id
          AND sub.school_id = ANY($1::uuid[])
    )
  )
`

func (q *Queries) CountParentsScoped(ctx context.Context, schoolIds []uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countParentsScoped, schoolIds)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countPlaybackStatsByCameraScoped = `-- name: CountPlaybackStatsByCameraScoped :many
SELECT
    al.camera_id,
    cam.name AS camera_name,
    COUNT(*)::bigint AS total,
    COUNT(*) FILTER (WHERE al.action = 'PLAYBACK_ACCESS_DENIED')::bigint AS denied
FROM audit_logs al
LEFT JOIN cameras cam ON cam.id = al.camera_id
WHERE al.action IN (
    'PLAYBACK_LIVE_REQUESTED',
    'PLAYBACK_TIMELINE_REQUESTED',
    'PLAYBACK_RECORDING_REQUESTED',
    'PLAYBACK_ACCESS_DENIED'
)
  AND al.created_at >= $1
  AND al.created_at < $2
  AND al.camera_id IS NOT NULL
  AND ($3::uuid[] IS NULL OR al.school_id = ANY($3::uuid[]))
  AND ($4::uuid IS NULL OR al.school_id = $4)
GROUP BY al.camera_id, cam.name
ORDER BY total DESC
LIMIT $5
`

type CountPlaybackStatsByCameraScopedParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	SchoolIds   []uuid.UUID        `json:"school_ids"`
	SchoolID    pgtype.UUID        `json:"school_id"`
	RowLimit    int32              `json:"row_limit"`
}

type CountPlaybackStatsByCameraScopedRow struct {
	CameraID   pgtype.UUID `json:"camera_id"`
	CameraName pgtype.Text `json:"camera_name"`
	Total      int64       `json:"total"`
	Denied     int64       `json:"denied"`
}

func (q *Queries) CountPlaybackStatsByCameraScoped(ctx context.Context, arg CountPlaybackStatsByCameraScopedParams) ([]CountPlaybackStatsByCameraScopedRow, error) {
	rows, err := q.db.Query(ctx, countPlaybackStatsByCameraScoped,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.SchoolIds,
		arg.SchoolID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountPlaybackStatsByCameraScopedRow{}
	for rows.Next() {
		var i CountPlaybackStatsByCameraScopedRow
		if err := rows.Scan(
			&i.CameraID,
			&i.CameraName,
			&i.Total,
			&i.Denied,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPlaybackStatsByDayScoped = `-- name: CountPlaybackStatsByDayScoped :many
SELECT
    (date_trunc('day', timezone($3::text, al.created_at)))::date AS day,
    COUNT(*)::bigint AS total,
    COUNT(*) FILTER (WHERE al.action = 'PLAYBACK_ACCESS_DENIED')::bigint AS denied,
    COUNT(DISTINCT al.user_id) FILTER (
        WHERE al.user_id IS NOT NULL
          AND al.action IN (
              'PLAYBACK_LIVE_REQUESTED',
              'PLAYBACK_TIMELINE_REQUESTED',
              'PLAYBACK_RECORDING_REQUESTED'
          )
          AND EXISTS (SELECT 1 FROM users u WHERE u.id = al.user_id AND u.role = 'PARENT')
    )::bigint AS unique_parents
FROM audit_logs al
WHERE al.action IN (
    'PLAYBACK_LIVE_REQUESTED',
    'PLAYBACK_TIMELINE_REQUESTED',
    'PLAYBACK_RECORDING_REQUESTED',
    'PLAYBACK_ACCESS_DENIED'
)
  AND al.created_at >= $1
  AND al.created_at < $2
  AND ($4::uuid[] IS NULL OR al.school_id = ANY($4::uuid[]))
  AND ($5::uuid IS NULL OR al.school_id = $5)
  AND ($6::uuid IS NULL OR al.camera_id = $6)
GROUP BY day
ORDER BY day ASC
`

type CountPlaybackStatsByDayScopedParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	TzName      string             `json:"tz_name"`
	SchoolIds   []uuid.UUID        `json:"school_ids"`
	SchoolID    pgtype.UUID        `json:"school_id"`
	CameraID    pgtype.UUID        `json:"camera_id"`
}

type CountPlaybackStatsByDayScopedRow struct {
	Day           pgtype.Date `json:"day"`
	Total         int64       `json:"total"`
	Denied        int64       `json:"denied"`
	UniqueParents int64       `json:"unique_parents"`
}

func (q *Queries) CountPlaybackStatsByDayScoped(ctx context.Context, arg CountPlaybackStatsByDayScopedParams) ([]CountPlaybackStatsByDayScopedRow, error) {
	rows, err := q.db.Query(ctx, countPlaybackStatsByDayScoped,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.TzName,
		arg.SchoolIds,
		arg.SchoolID,
		arg.CameraID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountPlaybackStatsByDayScopedRow{}
	for rows.Next() {
		var i CountPlaybackStatsByDayScopedRow
		if err := rows.Scan(
			&i.Day,
			&i.Total,
			&i.Denied,
			&i.UniqueParents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPlaybackStatsBySchoolScoped = `-- name: CountPlaybackStatsBySchoolScoped :many
SELECT
    al.school_id,
    s.name AS school_name,
    COUNT(*)::bigint AS total,
    COUNT(*) FILTER (WHERE al.action = 'PLAYBACK_ACCESS_DENIED')::bigint AS denied
FROM audit_logs al
LEFT JOIN schools s ON s.id = al.school_id
WHERE al.action IN (
    'PLAYBACK_LIVE_REQUESTED',
    'PLAYBACK_TIMELINE_REQUESTED',
    'PLAYBACK_RECORDING_REQUESTED',
    'PLAYBACK_ACCESS_DENIED'
)
  AND al.created_at >= $1
  AND al.created_at < $2
  AND al.school_id IS NOT NULL
  AND ($3::uuid[] IS NULL OR al.school_id = ANY($3::uuid[]))
GROUP BY al.school_id, s.name
ORDER BY total DESC
LIMIT $4
`

type CountPlaybackStatsBySchoolScopedParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	SchoolIds   []uuid.UUID        `json:"school_ids"`
	RowLimit    int32              `json:"row_limit"`
}

type CountPlaybackStatsBySchoolScopedRow struct {
	SchoolID   pgtype.UUID `json:"school_id"`
	SchoolName pgtype.Text `json:"school_name"`
	Total      int64       `json:"total"`
	Denied     int64       `json:"denied"`
}

func (q *Queries) CountPlaybackStatsBySchoolScoped(ctx context.Context, arg CountPlaybackStatsBySchoolScopedParams) ([]CountPlaybackStatsBySchoolScopedRow, error) {
	rows, err := q.db.Query(ctx, countPlaybackStatsBySchoolScoped,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.SchoolIds,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountPlaybackStatsBySchoolScopedRow{}
	for rows.Next() {
		var i CountPlaybackStatsBySchoolScopedRow
		if err := rows.Scan(
			&i.SchoolID,
			&i.SchoolName,
			&i.Total,
			&i.Denied,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPlaybackStatsScoped = `-- name: CountPlaybackStatsScoped :one
SELECT
    COUNT(*) FILTER (WHERE al.action = 'PLAYBACK_LIVE_REQUESTED')::bigint AS live_requests,
    COUNT(*) FILTER (WHERE al.action = 'PLAYBACK_TIMELINE_REQUESTED')::bigint AS timeline_requests,
    COUNT(*) FILTER (WHERE al.action = 'PLAYBACK_RECORDING_REQUESTED')::bigint AS recording_requests,
    COUNT(*) FILTER (WHERE al.action = 'PLAYBACK_ACCESS_DENIED')::bigint AS denied_requests,
    COUNT(*)::bigint AS total_requests
FROM audit_logs al
WHERE al.action IN (
    'PLAYBACK_LIVE_REQUESTED',
    'PLAYBACK_TIMELINE_REQUESTED',
    'PLAYBACK_RECORDING_REQUESTED',
    'PLAYBACK_ACCESS_DENIED'
)
  AND al.created_at >= $1
  AND al.created_at < $2
  AND ($3::uuid[] IS NULL OR al.school_id = ANY($3::uuid[]))
  AND ($4::uuid IS NULL OR al.school_id = $4)
  AND ($5::uuid IS NULL OR al.camera_id = $5)
`

type CountPlaybackStatsScopedParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	SchoolIds   []uuid.UUID        `json:"school_ids"`
	SchoolID    pgtype.UUID        `json:"school_id"`
	CameraID    pgtype.UUID        `json:"camera_id"`
}

type CountPlaybackStatsScopedRow struct {
	LiveRequests      int64 `json:"live_requests"`
	TimelineRequests  int64 `json:"timeline_requests"`
	RecordingRequests int64 `json:"recording_requests"`
	DeniedRequests    int64 `json:"denied_requests"`
	TotalRequests     int64 `json:"total_requests"`
}

func (q *Queries) CountPlaybackStatsScoped(ctx context.Context, arg CountPlaybackStatsScopedParams) (CountPlaybackStatsScopedRow, error) {
	row := q.db.QueryRow(ctx, countPlaybackStatsScoped,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.SchoolIds,
		arg.SchoolID,
		arg.CameraID,
	)
	var i CountPlaybackStatsScopedRow
	err := row.Scan(
		&i.LiveRequests,
		&i.TimelineRequests,
		&i.RecordingRequests,
		&i.DeniedRequests,
		&i.TotalRequests,
	)
	return i, err
}

const countSchoolsByStatusScoped = `-- name: CountSchoolsByStatusScoped :one
SELECT COUNT(*)::bigint AS total
FROM schools
WHERE status = $1
  AND ($2::uuid[] IS NULL OR id = ANY($2::uuid[]))
`

type CountSchoolsByStatusScopedParams struct {
	Status    string      `json:"status"`
	SchoolIds []uuid.UUID `json:"school_ids"`
}

func (q *Queries) CountSchoolsByStatusScoped(ctx context.Context, arg CountSchoolsByStatusScopedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSchoolsByStatusScoped, arg.Status, arg.SchoolIds)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countSchoolsScoped = `-- name: CountSchoolsScoped :one
SELECT COUNT(*)::bigint AS total
FROM schools
WHERE ($1::uuid[] IS NULL OR id = ANY($1::uuid[]))
`

func (q *Queries) CountSchoolsScoped(ctx context.Context, schoolIds []uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSchoolsScoped, schoolIds)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countSubscriptionsByStatusScoped = `-- name: CountSubscriptionsByStatusScoped :one
SELECT COUNT(*)::bigint AS total
FROM subscriptions sub
WHERE sub.status = $1
  AND ($2::uuid[] IS NULL OR sub.school_id = ANY($2::uuid[]))
`

type CountSubscriptionsByStatusScopedParams struct {
	Status    string      `json:"status"`
	SchoolIds []uuid.UUID `json:"school_ids"`
}

func (q *Queries) CountSubscriptionsByStatusScoped(ctx context.Context, arg CountSubscriptionsByStatusScopedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubscriptionsByStatusScoped, arg.Status, arg.SchoolIds)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countUniqueParentsPlaybackScoped = `-- name: CountUniqueParentsPlaybackScoped :one
SELECT COUNT(DISTINCT al.user_id)::bigint AS unique_parents
FROM audit_logs al
INNER JOIN users u ON u.id = al.user_id AND u.role = 'PARENT'
WHERE al.action IN (
    'PLAYBACK_LIVE_REQUESTED',
    'PLAYBACK_TIMELINE_REQUESTED',
    'PLAYBACK_RECORDING_REQUESTED'
)
  AND al.user_id IS NOT NULL
  AND al.created_at >= $1
  AND al.created_at < $2
  AND ($3::uuid[] IS NULL OR al.school_id = ANY($3::uuid[]))
  AND ($4::uuid IS NULL OR al.school_id = $4)
  AND ($5::uuid IS NULL OR al.camera_id = $5)
`

type CountUniqueParentsPlaybackScopedParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	SchoolIds   []uuid.UUID        `json:"school_ids"`
	SchoolID    pgtype.UUID        `json:"school_id"`
	CameraID    pgtype.UUID        `json:"camera_id"`
}

func (q *Queries) CountUniqueParentsPlaybackScoped(ctx context.Context, arg CountUniqueParentsPlaybackScopedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUniqueParentsPlaybackScoped,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.SchoolIds,
		arg.SchoolID,
		arg.CameraID,
	)
	var unique_parents int64
	err := row.Scan(&unique_parents)
	return unique_parents, err
}

const listAuditLogsFiltered = `-- name: ListAuditLogsFiltered :many
SELECT
    al.id,
    al.user_id,
    al.school_id,
    al.classroom_id,
    al.camera_id,
    al.child_id,
    al.device_id,
    al.action,
    al.ip_address,
    al.user_agent,
    al.metadata,
    al.created_at,
    u.full_name AS user_name,
    s.name AS school_name
FROM audit_logs al
LEFT JOIN users u ON u.id = al.user_id
LEFT JOIN schools s ON s.id = al.school_id
WHERE ($1::uuid[] IS NULL OR al.school_id = ANY($1::uuid[]))
  AND ($2::uuid IS NULL OR al.school_id = $2)
  AND ($3::uuid IS NULL OR al.user_id = $3)
  AND ($4::uuid IS NULL OR al.camera_id = $4)
  AND ($5::text IS NULL OR al.action = $5)
  AND ($6::timestamptz IS NULL OR al.created_at >= $6)
  AND ($7::timestamptz IS NULL OR al.created_at < $7)
ORDER BY al.created_at DESC
LIMIT $9 OFFSET $8
`

type ListAuditLogsFilteredParams struct {
	SchoolIds []uuid.UUID        `json:"school_ids"`
	SchoolID  pgtype.UUID        `json:"school_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CameraID  pgtype.UUID        `json:"camera_id"`
	Action    pgtype.Text        `json:"action"`
	DateFrom  pgtype.Timestamptz `json:"date_from"`
	DateTo    pgtype.Timestamptz `json:"date_to"`
	RowOffset int32              `json:"row_offset"`
	RowLimit  int32              `json:"row_limit"`
}

type ListAuditLogsFilteredRow struct {
	ID          uuid.UUID          `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	SchoolID    pgtype.UUID        `json:"school_id"`
	ClassroomID pgtype.UUID        `json:"classroom_id"`
	CameraID    pgtype.UUID        `json:"camera_id"`
	ChildID     pgtype.UUID        `json:"child_id"`
	DeviceID    pgtype.UUID        `json:"device_id"`
	Action      string             `json:"action"`
	IpAddress   pgtype.Text        `json:"ip_address"`
	UserAgent   pgtype.Text        `json:"user_agent"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UserName    pgtype.Text        `json:"user_name"`
	SchoolName  pgtype.Text        `json:"school_name"`
}

func (q *Queries) ListAuditLogsFiltered(ctx context.Context, arg ListAuditLogsFilteredParams) ([]ListAuditLogsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogsFiltered,
		arg.SchoolIds,
		arg.SchoolID,
		arg.UserID,
		arg.CameraID,
		arg.Action,
		arg.DateFrom,
		arg.DateTo,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsFilteredRow{}
	for rows.Next() {
		var i ListAuditLogsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SchoolID,
			&i.ClassroomID,
			&i.CameraID,
			&i.ChildID,
			&i.DeviceID,
			&i.Action,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
			&i.UserName,
			&i.SchoolName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCameraStatusBySchool = `-- name: ListCameraStatusBySchool :many
SELECT
    cam.id AS camera_id,
    cam.name AS camera_name,
    cr.name AS classroom_name,
    cam.status,
    COALESCE(css.desired_state, 'STOPPED')::text AS desired_state,
    cam.default_quality,
    cam.last_segment_at,
    (
        SELECT COUNT(*)::bigint
        FROM alerts a
        WHERE a.camera_id = cam.id
          AND a.status IN ('OPEN', 'ACKNOWLEDGED')
    ) AS open_alerts,
    (
        SELECT che.event_type
        FROM camera_health_events che
        WHERE che.camera_id = cam.id
        ORDER BY che.created_at DESC
        LIMIT 1
    ) AS last_health_event
FROM cameras cam
LEFT JOIN classrooms cr ON cr.id = cam.classroom_id
LEFT JOIN camera_stream_states css ON css.camera_id = cam.id
WHERE cam.school_id = $1
ORDER BY cam.name
`

type ListCameraStatusBySchoolRow struct {
	CameraID        uuid.UUID          `json:"camera_id"`
	CameraName      string             `json:"camera_name"`
	ClassroomName   pgtype.Text        `json:"classroom_name"`
	Status          string             `json:"status"`
	DesiredState    string             `json:"desired_state"`
	DefaultQuality  string             `json:"default_quality"`
	LastSegmentAt   pgtype.Timestamptz `json:"last_segment_at"`
	OpenAlerts      int64              `json:"open_alerts"`
	LastHealthEvent string             `json:"last_health_event"`
}

func (q *Queries) ListCameraStatusBySchool(ctx context.Context, schoolID uuid.UUID) ([]ListCameraStatusBySchoolRow, error) {
	rows, err := q.db.Query(ctx, listCameraStatusBySchool, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCameraStatusBySchoolRow{}
	for rows.Next() {
		var i ListCameraStatusBySchoolRow
		if err := rows.Scan(
			&i.CameraID,
			&i.CameraName,
			&i.ClassroomName,
			&i.Status,
			&i.DesiredState,
			&i.DefaultQuality,
			&i.LastSegmentAt,
			&i.OpenAlerts,
			&i.LastHealthEvent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestWorkerHeartbeats = `-- name: ListLatestWorkerHeartbeats :many
SELECT DISTINCT ON (worker_name)
    id,
    worker_name,
    worker_type,
    status,
    metadata,
    last_seen_at,
    created_at
FROM worker_heartbeats
ORDER BY worker_name, last_seen_at DESC
`

func (q *Queries) ListLatestWorkerHeartbeats(ctx context.Context) ([]WorkerHeartbeat, error) {
	rows, err := q.db.Query(ctx, listLatestWorkerHeartbeats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkerHeartbeat{}
	for rows.Next() {
		var i WorkerHeartbeat
		if err := rows.Scan(
			&i.ID,
			&i.WorkerName,
			&i.WorkerType,
			&i.Status,
			&i.Metadata,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumApprovedPaymentsCentsScoped = `-- name: SumApprovedPaymentsCentsScoped :one
SELECT COALESCE(SUM(p.amount_cents), 0)::bigint AS total_cents
FROM payments p
WHERE p.status = 'APPROVED'
  AND p.approved_at >= $1
  AND p.approved_at < $2
  AND ($3::uuid[] IS NULL OR p.school_id = ANY($3::uuid[]))
`

type SumApprovedPaymentsCentsScopedParams struct {
	ApprovedAt   pgtype.Timestamptz `json:"approved_at"`
	ApprovedAt_2 pgtype.Timestamptz `json:"approved_at_2"`
	SchoolIds    []uuid.UUID        `json:"school_ids"`
}

func (q *Queries) SumApprovedPaymentsCentsScoped(ctx context.Context, arg SumApprovedPaymentsCentsScopedParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumApprovedPaymentsCentsScoped, arg.ApprovedAt, arg.ApprovedAt_2, arg.SchoolIds)
	var total_cents int64
	err := row.Scan(&total_cents)
	return total_cents, err
}

const sumLatestStorageBytesScoped = `-- name: SumLatestStorageBytesScoped :one
SELECT COALESCE(SUM(latest.total_bytes), 0)::bigint AS total_bytes
FROM (
    SELECT DISTINCT ON (su.school_id)
        su.total_bytes
    FROM storage_usage su
    WHERE ($1::uuid[] IS NULL OR su.school_id = ANY($1::uuid[]))
    ORDER BY su.school_id, su.date DESC
) latest
`

func (q *Queries) SumLatestStorageBytesScoped(ctx context.Context, schoolIds []uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumLatestStorageBytesScoped, schoolIds)
	var total_bytes int64
	err := row.Scan(&total_bytes)
	return total_bytes, err
}

const sumPendingPaymentsCentsScoped = `-- name: SumPendingPaymentsCentsScoped :one
SELECT COALESCE(SUM(p.amount_cents), 0)::bigint AS total_cents
FROM payments p
WHERE p.status = 'PENDING'
  AND ($1::uuid[] IS NULL OR p.school_id = ANY($1::uuid[]))
`

func (q *Queries) SumPendingPaymentsCentsScoped(ctx context.Context, schoolIds []uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumPendingPaymentsCentsScoped, schoolIds)
	var total_cents int64
	err := row.Scan(&total_cents)
	return total_cents, err
}
