// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playback.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCameraWithSchoolClassroom = `-- name: GetCameraWithSchoolClassroom :one
SELECT
    cam.id,
    cam.school_id,
    cam.classroom_id,
    cam.name,
    cam.r2_live_path,
    cam.r2_recording_path,
    cam.default_quality,
    cam.status AS camera_status,
    s.name AS school_name,
    s.status AS school_status,
    cr.name AS classroom_name,
    cr.status AS classroom_status
FROM cameras cam
INNER JOIN schools s ON s.id = cam.school_id
LEFT JOIN classrooms cr ON cr.id = cam.classroom_id
WHERE cam.id = $1
`

type GetCameraWithSchoolClassroomRow struct {
	ID              uuid.UUID   `json:"id"`
	SchoolID        uuid.UUID   `json:"school_id"`
	ClassroomID     pgtype.UUID `json:"classroom_id"`
	Name            string      `json:"name"`
	R2LivePath      string      `json:"r2_live_path"`
	R2RecordingPath pgtype.Text `json:"r2_recording_path"`
	DefaultQuality  string      `json:"default_quality"`
	CameraStatus    string      `json:"camera_status"`
	SchoolName      string      `json:"school_name"`
	SchoolStatus    string      `json:"school_status"`
	ClassroomName   pgtype.Text `json:"classroom_name"`
	ClassroomStatus pgtype.Text `json:"classroom_status"`
}

func (q *Queries) GetCameraWithSchoolClassroom(ctx context.Context, id uuid.UUID) (GetCameraWithSchoolClassroomRow, error) {
	row := q.db.QueryRow(ctx, getCameraWithSchoolClassroom, id)
	var i GetCameraWithSchoolClassroomRow
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.ClassroomID,
		&i.Name,
		&i.R2LivePath,
		&i.R2RecordingPath,
		&i.DefaultQuality,
		&i.CameraStatus,
		&i.SchoolName,
		&i.SchoolStatus,
		&i.ClassroomName,
		&i.ClassroomStatus,
	)
	return i, err
}

const getParentChildIDForCamera = `-- name: GetParentChildIDForCamera :one
SELECT ch.id
FROM parent_children pc
INNER JOIN children ch ON ch.id = pc.child_id AND ch.status = 'ACTIVE'
INNER JOIN cameras cam ON cam.classroom_id = ch.classroom_id AND cam.id = $2
WHERE pc.parent_id = $1
LIMIT 1
`

type GetParentChildIDForCameraParams struct {
	ParentID uuid.UUID `json:"parent_id"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) GetParentChildIDForCamera(ctx context.Context, arg GetParentChildIDForCameraParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getParentChildIDForCamera, arg.ParentID, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listRecordingSegmentsByCameraDate = `-- name: ListRecordingSegmentsByCameraDate :many
SELECT id, camera_id, school_id, segment_path, playlist_path, quality, start_time, end_time, duration_seconds, size_bytes, created_at, expires_at
FROM recording_segments
WHERE camera_id = $1
  AND expires_at > NOW()
  AND start_time >= $2
  AND start_time < $3
  AND ($4::text = '' OR quality = $4)
ORDER BY start_time ASC
`

type ListRecordingSegmentsByCameraDateParams struct {
	CameraID    uuid.UUID          `json:"camera_id"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	StartTime_2 pgtype.Timestamptz `json:"start_time_2"`
	Column4     string             `json:"column_4"`
}

func (q *Queries) ListRecordingSegmentsByCameraDate(ctx context.Context, arg ListRecordingSegmentsByCameraDateParams) ([]RecordingSegment, error) {
	rows, err := q.db.Query(ctx, listRecordingSegmentsByCameraDate,
		arg.CameraID,
		arg.StartTime,
		arg.StartTime_2,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecordingSegment{}
	for rows.Next() {
		var i RecordingSegment
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.SchoolID,
			&i.SegmentPath,
			&i.PlaylistPath,
			&i.Quality,
			&i.StartTime,
			&i.EndTime,
			&i.DurationSeconds,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordingSegmentsByCameraRange = `-- name: ListRecordingSegmentsByCameraRange :many
SELECT id, camera_id, school_id, segment_path, playlist_path, quality, start_time, end_time, duration_seconds, size_bytes, created_at, expires_at
FROM recording_segments
WHERE camera_id = $1
  AND expires_at > NOW()
  AND start_time < $3
  AND end_time > $2
  AND ($4::text = '' OR quality = $4)
ORDER BY start_time ASC
`

type ListRecordingSegmentsByCameraRangeParams struct {
	CameraID  uuid.UUID          `json:"camera_id"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	Column4   string             `json:"column_4"`
}

func (q *Queries) ListRecordingSegmentsByCameraRange(ctx context.Context, arg ListRecordingSegmentsByCameraRangeParams) ([]RecordingSegment, error) {
	rows, err := q.db.Query(ctx, listRecordingSegmentsByCameraRange,
		arg.CameraID,
		arg.EndTime,
		arg.StartTime,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecordingSegment{}
	for rows.Next() {
		var i RecordingSegment
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.SchoolID,
			&i.SegmentPath,
			&i.PlaylistPath,
			&i.Quality,
			&i.StartTime,
			&i.EndTime,
			&i.DurationSeconds,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const parentCanAccessCamera = `-- name: ParentCanAccessCamera :one
SELECT EXISTS (
    SELECT 1
    FROM parent_children pc
    INNER JOIN children ch ON ch.id = pc.child_id AND ch.status = 'ACTIVE'
    INNER JOIN cameras cam ON cam.classroom_id = ch.classroom_id AND cam.id = $2
    WHERE pc.parent_id = $1
) AS can_access
`

type ParentCanAccessCameraParams struct {
	ParentID uuid.UUID `json:"parent_id"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) ParentCanAccessCamera(ctx context.Context, arg ParentCanAccessCameraParams) (bool, error) {
	row := q.db.QueryRow(ctx, parentCanAccessCamera, arg.ParentID, arg.ID)
	var can_access bool
	err := row.Scan(&can_access)
	return can_access, err
}
