// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recording_segments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertRecordingSegment = `-- name: InsertRecordingSegment :one
INSERT INTO recording_segments (
    id,
    camera_id,
    school_id,
    segment_path,
    playlist_path,
    quality,
    start_time,
    end_time,
    duration_seconds,
    size_bytes,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, camera_id, school_id, segment_path, playlist_path, quality, start_time, end_time, duration_seconds, size_bytes, created_at, expires_at
`

type InsertRecordingSegmentParams struct {
	ID              uuid.UUID          `json:"id"`
	CameraID        uuid.UUID          `json:"camera_id"`
	SchoolID        uuid.UUID          `json:"school_id"`
	SegmentPath     string             `json:"segment_path"`
	PlaylistPath    pgtype.Text        `json:"playlist_path"`
	Quality         string             `json:"quality"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	DurationSeconds int32              `json:"duration_seconds"`
	SizeBytes       int64              `json:"size_bytes"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertRecordingSegment(ctx context.Context, arg InsertRecordingSegmentParams) (RecordingSegment, error) {
	row := q.db.QueryRow(ctx, insertRecordingSegment,
		arg.ID,
		arg.CameraID,
		arg.SchoolID,
		arg.SegmentPath,
		arg.PlaylistPath,
		arg.Quality,
		arg.StartTime,
		arg.EndTime,
		arg.DurationSeconds,
		arg.SizeBytes,
		arg.ExpiresAt,
	)
	var i RecordingSegment
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.SchoolID,
		&i.SegmentPath,
		&i.PlaylistPath,
		&i.Quality,
		&i.StartTime,
		&i.EndTime,
		&i.DurationSeconds,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listSegmentsByCameraAndTimeRange = `-- name: ListSegmentsByCameraAndTimeRange :many
SELECT id, camera_id, school_id, segment_path, playlist_path, quality, start_time, end_time, duration_seconds, size_bytes, created_at, expires_at FROM recording_segments
WHERE camera_id = $1
  AND start_time >= $2
  AND end_time <= $3
ORDER BY start_time ASC
`

type ListSegmentsByCameraAndTimeRangeParams struct {
	CameraID  uuid.UUID          `json:"camera_id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	EndTime   pgtype.Timestamptz `json:"end_time"`
}

func (q *Queries) ListSegmentsByCameraAndTimeRange(ctx context.Context, arg ListSegmentsByCameraAndTimeRangeParams) ([]RecordingSegment, error) {
	rows, err := q.db.Query(ctx, listSegmentsByCameraAndTimeRange, arg.CameraID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecordingSegment{}
	for rows.Next() {
		var i RecordingSegment
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.SchoolID,
			&i.SegmentPath,
			&i.PlaylistPath,
			&i.Quality,
			&i.StartTime,
			&i.EndTime,
			&i.DurationSeconds,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
