// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    id,
    user_id,
    token_hash,
    device_id,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, token_hash, device_id, expires_at, revoked_at, replaced_by_token_hash, created_at
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	DeviceID  pgtype.UUID        `json:"device_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.DeviceID,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedByTokenHash,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, device_id, expires_at, revoked_at, replaced_by_token_hash, created_at FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedByTokenHash,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW(),
    replaced_by_token_hash = $2
WHERE token_hash = $1
  AND revoked_at IS NULL
`

type RevokeRefreshTokenParams struct {
	TokenHash           string      `json:"token_hash"`
	ReplacedByTokenHash pgtype.Text `json:"replaced_by_token_hash"`
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, arg.TokenHash, arg.ReplacedByTokenHash)
	return err
}

const revokeUserDeviceTokens = `-- name: RevokeUserDeviceTokens :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE user_id = $1
  AND device_id = $2
  AND revoked_at IS NULL
`

type RevokeUserDeviceTokensParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	DeviceID pgtype.UUID `json:"device_id"`
}

func (q *Queries) RevokeUserDeviceTokens(ctx context.Context, arg RevokeUserDeviceTokensParams) error {
	_, err := q.db.Exec(ctx, revokeUserDeviceTokens, arg.UserID, arg.DeviceID)
	return err
}
