// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countStorageUsageBySchool = `-- name: CountStorageUsageBySchool :one
SELECT
    COALESCE(SUM(size_bytes), 0)::bigint AS total_bytes,
    COUNT(*)::bigint AS segment_count
FROM recording_segments
WHERE school_id = $1
  AND expires_at > NOW()
`

type CountStorageUsageBySchoolRow struct {
	TotalBytes   int64 `json:"total_bytes"`
	SegmentCount int64 `json:"segment_count"`
}

func (q *Queries) CountStorageUsageBySchool(ctx context.Context, schoolID uuid.UUID) (CountStorageUsageBySchoolRow, error) {
	row := q.db.QueryRow(ctx, countStorageUsageBySchool, schoolID)
	var i CountStorageUsageBySchoolRow
	err := row.Scan(&i.TotalBytes, &i.SegmentCount)
	return i, err
}

const deleteRecordingSegmentsByIDs = `-- name: DeleteRecordingSegmentsByIDs :execrows
DELETE FROM recording_segments
WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteRecordingSegmentsByIDs(ctx context.Context, dollar_1 []uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRecordingSegmentsByIDs, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listExpiredRecordingSegments = `-- name: ListExpiredRecordingSegments :many
SELECT id, camera_id, school_id, segment_path, playlist_path, quality, start_time, end_time, duration_seconds, size_bytes, created_at, expires_at
FROM recording_segments
WHERE expires_at < NOW()
ORDER BY expires_at ASC
LIMIT $1
`

func (q *Queries) ListExpiredRecordingSegments(ctx context.Context, limit int32) ([]RecordingSegment, error) {
	rows, err := q.db.Query(ctx, listExpiredRecordingSegments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecordingSegment{}
	for rows.Next() {
		var i RecordingSegment
		if err := rows.Scan(
			&i.ID,
			&i.CameraID,
			&i.SchoolID,
			&i.SegmentPath,
			&i.PlaylistPath,
			&i.Quality,
			&i.StartTime,
			&i.EndTime,
			&i.DurationSeconds,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchoolsForStorageReport = `-- name: ListSchoolsForStorageReport :many
SELECT id, name, status
FROM schools
ORDER BY name
`

type ListSchoolsForStorageReportRow struct {
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Status string    `json:"status"`
}

func (q *Queries) ListSchoolsForStorageReport(ctx context.Context) ([]ListSchoolsForStorageReportRow, error) {
	rows, err := q.db.Query(ctx, listSchoolsForStorageReport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchoolsForStorageReportRow{}
	for rows.Next() {
		var i ListSchoolsForStorageReportRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStorageUsageReport = `-- name: ListStorageUsageReport :many
SELECT
    su.id,
    su.school_id,
    s.name AS school_name,
    su.date,
    su.total_bytes,
    su.segment_count,
    su.estimated_cost_usd,
    su.metadata,
    su.created_at,
    su.updated_at
FROM storage_usage su
INNER JOIN schools s ON s.id = su.school_id
WHERE ($1::uuid[] IS NULL OR su.school_id = ANY($1::uuid[]))
  AND ($2::uuid IS NULL OR su.school_id = $2)
  AND ($3::date IS NULL OR su.date >= $3::date)
  AND ($4::date IS NULL OR su.date <= $4::date)
ORDER BY su.date DESC, s.name ASC
LIMIT $5
`

type ListStorageUsageReportParams struct {
	SchoolIds []uuid.UUID `json:"school_ids"`
	SchoolID  pgtype.UUID `json:"school_id"`
	DateFrom  pgtype.Date `json:"date_from"`
	DateTo    pgtype.Date `json:"date_to"`
	RowLimit  int32       `json:"row_limit"`
}

type ListStorageUsageReportRow struct {
	ID               uuid.UUID          `json:"id"`
	SchoolID         uuid.UUID          `json:"school_id"`
	SchoolName       string             `json:"school_name"`
	Date             pgtype.Date        `json:"date"`
	TotalBytes       int64              `json:"total_bytes"`
	SegmentCount     int64              `json:"segment_count"`
	EstimatedCostUsd pgtype.Numeric     `json:"estimated_cost_usd"`
	Metadata         []byte             `json:"metadata"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListStorageUsageReport(ctx context.Context, arg ListStorageUsageReportParams) ([]ListStorageUsageReportRow, error) {
	rows, err := q.db.Query(ctx, listStorageUsageReport,
		arg.SchoolIds,
		arg.SchoolID,
		arg.DateFrom,
		arg.DateTo,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStorageUsageReportRow{}
	for rows.Next() {
		var i ListStorageUsageReportRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.SchoolName,
			&i.Date,
			&i.TotalBytes,
			&i.SegmentCount,
			&i.EstimatedCostUsd,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStorageUsage = `-- name: UpsertStorageUsage :one
INSERT INTO storage_usage (
    id,
    school_id,
    date,
    total_bytes,
    segment_count,
    estimated_cost_usd,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (school_id, date) DO UPDATE SET
    total_bytes = EXCLUDED.total_bytes,
    segment_count = EXCLUDED.segment_count,
    estimated_cost_usd = EXCLUDED.estimated_cost_usd,
    metadata = EXCLUDED.metadata,
    updated_at = NOW()
RETURNING id, school_id, date, total_bytes, segment_count, estimated_cost_usd, metadata, created_at, updated_at
`

type UpsertStorageUsageParams struct {
	ID               uuid.UUID      `json:"id"`
	SchoolID         uuid.UUID      `json:"school_id"`
	Date             pgtype.Date    `json:"date"`
	TotalBytes       int64          `json:"total_bytes"`
	SegmentCount     int64          `json:"segment_count"`
	EstimatedCostUsd pgtype.Numeric `json:"estimated_cost_usd"`
	Metadata         []byte         `json:"metadata"`
}

func (q *Queries) UpsertStorageUsage(ctx context.Context, arg UpsertStorageUsageParams) (StorageUsage, error) {
	row := q.db.QueryRow(ctx, upsertStorageUsage,
		arg.ID,
		arg.SchoolID,
		arg.Date,
		arg.TotalBytes,
		arg.SegmentCount,
		arg.EstimatedCostUsd,
		arg.Metadata,
	)
	var i StorageUsage
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.Date,
		&i.TotalBytes,
		&i.SegmentCount,
		&i.EstimatedCostUsd,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
