// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedule.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSchoolScheduleSettings = `-- name: GetSchoolScheduleSettings :one
SELECT school_id, timezone, open_days, open_time, close_time, live_enabled, temporary_live_paused, temporary_live_pause_reason, created_at, updated_at
FROM school_schedule_settings
WHERE school_id = $1
`

func (q *Queries) GetSchoolScheduleSettings(ctx context.Context, schoolID uuid.UUID) (SchoolScheduleSettings, error) {
	row := q.db.QueryRow(ctx, getSchoolScheduleSettings, schoolID)
	var i SchoolScheduleSettings
	err := row.Scan(
		&i.SchoolID,
		&i.Timezone,
		&i.OpenDays,
		&i.OpenTime,
		&i.CloseTime,
		&i.LiveEnabled,
		&i.TemporaryLivePaused,
		&i.TemporaryLivePauseReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSchoolScheduleSettings = `-- name: UpsertSchoolScheduleSettings :one
INSERT INTO school_schedule_settings (
    school_id,
    timezone,
    open_days,
    open_time,
    close_time,
    live_enabled,
    temporary_live_paused,
    temporary_live_pause_reason
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (school_id) DO UPDATE SET
    timezone                    = EXCLUDED.timezone,
    open_days                   = EXCLUDED.open_days,
    open_time                   = EXCLUDED.open_time,
    close_time                  = EXCLUDED.close_time,
    live_enabled                = EXCLUDED.live_enabled,
    temporary_live_paused       = EXCLUDED.temporary_live_paused,
    temporary_live_pause_reason = EXCLUDED.temporary_live_pause_reason,
    updated_at                  = NOW()
RETURNING school_id, timezone, open_days, open_time, close_time, live_enabled, temporary_live_paused, temporary_live_pause_reason, created_at, updated_at
`

type UpsertSchoolScheduleSettingsParams struct {
	SchoolID                 uuid.UUID   `json:"school_id"`
	Timezone                 string      `json:"timezone"`
	OpenDays                 string      `json:"open_days"`
	OpenTime                 string      `json:"open_time"`
	CloseTime                string      `json:"close_time"`
	LiveEnabled              bool        `json:"live_enabled"`
	TemporaryLivePaused      bool        `json:"temporary_live_paused"`
	TemporaryLivePauseReason pgtype.Text `json:"temporary_live_pause_reason"`
}

func (q *Queries) UpsertSchoolScheduleSettings(ctx context.Context, arg UpsertSchoolScheduleSettingsParams) (SchoolScheduleSettings, error) {
	row := q.db.QueryRow(ctx, upsertSchoolScheduleSettings,
		arg.SchoolID,
		arg.Timezone,
		arg.OpenDays,
		arg.OpenTime,
		arg.CloseTime,
		arg.LiveEnabled,
		arg.TemporaryLivePaused,
		arg.TemporaryLivePauseReason,
	)
	var i SchoolScheduleSettings
	err := row.Scan(
		&i.SchoolID,
		&i.Timezone,
		&i.OpenDays,
		&i.OpenTime,
		&i.CloseTime,
		&i.LiveEnabled,
		&i.TemporaryLivePaused,
		&i.TemporaryLivePauseReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
