// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: scheduler.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCameraStreamStatesByDesiredState = `-- name: CountCameraStreamStatesByDesiredState :one
SELECT COUNT(*)::bigint
FROM camera_stream_states css
INNER JOIN cameras cam ON cam.id = css.camera_id
INNER JOIN schools s ON s.id = cam.school_id AND s.status = 'ACTIVE'
INNER JOIN classrooms cr ON cr.id = cam.classroom_id AND cr.status = 'ACTIVE'
WHERE cam.status IN ('ACTIVE', 'OFFLINE')
  AND css.desired_state = $1
`

func (q *Queries) CountCameraStreamStatesByDesiredState(ctx context.Context, desiredState string) (int64, error) {
	row := q.db.QueryRow(ctx, countCameraStreamStatesByDesiredState, desiredState)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getCameraStreamState = `-- name: GetCameraStreamState :one
SELECT camera_id, desired_state, reason, updated_at, created_at
FROM camera_stream_states
WHERE camera_id = $1
`

func (q *Queries) GetCameraStreamState(ctx context.Context, cameraID uuid.UUID) (CameraStreamState, error) {
	row := q.db.QueryRow(ctx, getCameraStreamState, cameraID)
	var i CameraStreamState
	err := row.Scan(
		&i.CameraID,
		&i.DesiredState,
		&i.Reason,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCameraStreamStates = `-- name: ListCameraStreamStates :many
SELECT camera_id, desired_state, reason, updated_at, created_at
FROM camera_stream_states
ORDER BY updated_at DESC
LIMIT $1
`

func (q *Queries) ListCameraStreamStates(ctx context.Context, limit int32) ([]CameraStreamState, error) {
	rows, err := q.db.Query(ctx, listCameraStreamStates, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CameraStreamState{}
	for rows.Next() {
		var i CameraStreamState
		if err := rows.Scan(
			&i.CameraID,
			&i.DesiredState,
			&i.Reason,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCamerasForScheduler = `-- name: ListCamerasForScheduler :many
SELECT
    cam.id,
    cam.school_id,
    cam.status
FROM cameras cam
INNER JOIN schools s ON s.id = cam.school_id AND s.status = 'ACTIVE'
INNER JOIN classrooms cr ON cr.id = cam.classroom_id AND cr.status = 'ACTIVE'
WHERE cam.status IN ('ACTIVE', 'OFFLINE')
ORDER BY cam.school_id, cam.name
`

type ListCamerasForSchedulerRow struct {
	ID       uuid.UUID `json:"id"`
	SchoolID uuid.UUID `json:"school_id"`
	Status   string    `json:"status"`
}

func (q *Queries) ListCamerasForScheduler(ctx context.Context) ([]ListCamerasForSchedulerRow, error) {
	rows, err := q.db.Query(ctx, listCamerasForScheduler)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCamerasForSchedulerRow{}
	for rows.Next() {
		var i ListCamerasForSchedulerRow
		if err := rows.Scan(&i.ID, &i.SchoolID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningDesiredCameras = `-- name: ListRunningDesiredCameras :many
SELECT css.camera_id, css.desired_state, css.reason, css.updated_at, css.created_at
FROM camera_stream_states css
INNER JOIN cameras cam ON cam.id = css.camera_id
INNER JOIN schools s ON s.id = cam.school_id AND s.status = 'ACTIVE'
INNER JOIN classrooms cr ON cr.id = cam.classroom_id AND cr.status = 'ACTIVE'
WHERE cam.status IN ('ACTIVE', 'OFFLINE')
  AND css.desired_state = 'RUNNING'
ORDER BY css.updated_at DESC
`

func (q *Queries) ListRunningDesiredCameras(ctx context.Context) ([]CameraStreamState, error) {
	rows, err := q.db.Query(ctx, listRunningDesiredCameras)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CameraStreamState{}
	for rows.Next() {
		var i CameraStreamState
		if err := rows.Scan(
			&i.CameraID,
			&i.DesiredState,
			&i.Reason,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAllActiveCamerasDesiredState = `-- name: SetAllActiveCamerasDesiredState :execrows
UPDATE camera_stream_states css
SET desired_state = $1,
    reason = $2,
    updated_at = NOW()
FROM cameras cam
INNER JOIN schools s ON s.id = cam.school_id AND s.status = 'ACTIVE'
INNER JOIN classrooms cr ON cr.id = cam.classroom_id AND cr.status = 'ACTIVE'
WHERE css.camera_id = cam.id
  AND cam.status IN ('ACTIVE', 'OFFLINE')
`

type SetAllActiveCamerasDesiredStateParams struct {
	DesiredState string      `json:"desired_state"`
	Reason       pgtype.Text `json:"reason"`
}

func (q *Queries) SetAllActiveCamerasDesiredState(ctx context.Context, arg SetAllActiveCamerasDesiredStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAllActiveCamerasDesiredState, arg.DesiredState, arg.Reason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertCameraStreamState = `-- name: UpsertCameraStreamState :one
INSERT INTO camera_stream_states (
    camera_id,
    desired_state,
    reason
) VALUES (
    $1, $2, $3
)
ON CONFLICT (camera_id) DO UPDATE SET
    desired_state = EXCLUDED.desired_state,
    reason = EXCLUDED.reason,
    updated_at = NOW()
RETURNING camera_id, desired_state, reason, updated_at, created_at
`

type UpsertCameraStreamStateParams struct {
	CameraID     uuid.UUID   `json:"camera_id"`
	DesiredState string      `json:"desired_state"`
	Reason       pgtype.Text `json:"reason"`
}

func (q *Queries) UpsertCameraStreamState(ctx context.Context, arg UpsertCameraStreamStateParams) (CameraStreamState, error) {
	row := q.db.QueryRow(ctx, upsertCameraStreamState, arg.CameraID, arg.DesiredState, arg.Reason)
	var i CameraStreamState
	err := row.Scan(
		&i.CameraID,
		&i.DesiredState,
		&i.Reason,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
