// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: schools.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSchool = `-- name: CreateSchool :one
INSERT INTO schools (
    id,
    name,
    address,
    phone,
    status
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, name, address, phone, status, created_at, updated_at
`

type CreateSchoolParams struct {
	ID      uuid.UUID   `json:"id"`
	Name    string      `json:"name"`
	Address pgtype.Text `json:"address"`
	Phone   pgtype.Text `json:"phone"`
	Status  string      `json:"status"`
}

func (q *Queries) CreateSchool(ctx context.Context, arg CreateSchoolParams) (School, error) {
	row := q.db.QueryRow(ctx, createSchool,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.Status,
	)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSchool = `-- name: GetSchool :one
SELECT id, name, address, phone, status, created_at, updated_at FROM schools
WHERE id = $1
`

func (q *Queries) GetSchool(ctx context.Context, id uuid.UUID) (School, error) {
	row := q.db.QueryRow(ctx, getSchool, id)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSchools = `-- name: ListSchools :many
SELECT id, name, address, phone, status, created_at, updated_at FROM schools
ORDER BY created_at DESC
`

func (q *Queries) ListSchools(ctx context.Context) ([]School, error) {
	rows, err := q.db.Query(ctx, listSchools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []School{}
	for rows.Next() {
		var i School
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchool = `-- name: UpdateSchool :one
UPDATE schools
SET
    name = COALESCE($1, name),
    address = COALESCE($2, address),
    phone = COALESCE($3, phone),
    status = COALESCE($4, status),
    updated_at = NOW()
WHERE id = $5
RETURNING id, name, address, phone, status, created_at, updated_at
`

type UpdateSchoolParams struct {
	Name    pgtype.Text `json:"name"`
	Address pgtype.Text `json:"address"`
	Phone   pgtype.Text `json:"phone"`
	Status  pgtype.Text `json:"status"`
	ID      uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateSchool(ctx context.Context, arg UpdateSchoolParams) (School, error) {
	row := q.db.QueryRow(ctx, updateSchool,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.Status,
		arg.ID,
	)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSchoolLimited = `-- name: UpdateSchoolLimited :one
UPDATE schools
SET
    address = COALESCE($1, address),
    phone = COALESCE($2, phone),
    updated_at = NOW()
WHERE id = $3
RETURNING id, name, address, phone, status, created_at, updated_at
`

type UpdateSchoolLimitedParams struct {
	Address pgtype.Text `json:"address"`
	Phone   pgtype.Text `json:"phone"`
	ID      uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateSchoolLimited(ctx context.Context, arg UpdateSchoolLimitedParams) (School, error) {
	row := q.db.QueryRow(ctx, updateSchoolLimited, arg.Address, arg.Phone, arg.ID)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
