// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: school_admins.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignSchoolAdmin = `-- name: AssignSchoolAdmin :one
INSERT INTO school_admins (school_id, user_id)
VALUES ($1, $2)
ON CONFLICT (school_id, user_id) DO UPDATE SET created_at = school_admins.created_at
RETURNING school_id, user_id, created_at
`

type AssignSchoolAdminParams struct {
	SchoolID uuid.UUID `json:"school_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) AssignSchoolAdmin(ctx context.Context, arg AssignSchoolAdminParams) (SchoolAdmin, error) {
	row := q.db.QueryRow(ctx, assignSchoolAdmin, arg.SchoolID, arg.UserID)
	var i SchoolAdmin
	err := row.Scan(&i.SchoolID, &i.UserID, &i.CreatedAt)
	return i, err
}

const isUserSchoolAdmin = `-- name: IsUserSchoolAdmin :one
SELECT EXISTS (
    SELECT 1 FROM school_admins
    WHERE school_id = $1 AND user_id = $2
) AS is_admin
`

type IsUserSchoolAdminParams struct {
	SchoolID uuid.UUID `json:"school_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) IsUserSchoolAdmin(ctx context.Context, arg IsUserSchoolAdminParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserSchoolAdmin, arg.SchoolID, arg.UserID)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const listSchoolAdminsForSchool = `-- name: ListSchoolAdminsForSchool :many
SELECT u.id, u.full_name, u.email, u.phone, u.role, u.status, sa.created_at AS assigned_at
FROM school_admins sa
INNER JOIN users u ON u.id = sa.user_id
WHERE sa.school_id = $1
ORDER BY sa.created_at
`

type ListSchoolAdminsForSchoolRow struct {
	ID         uuid.UUID          `json:"id"`
	FullName   string             `json:"full_name"`
	Email      pgtype.Text        `json:"email"`
	Phone      pgtype.Text        `json:"phone"`
	Role       string             `json:"role"`
	Status     string             `json:"status"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}

func (q *Queries) ListSchoolAdminsForSchool(ctx context.Context, schoolID uuid.UUID) ([]ListSchoolAdminsForSchoolRow, error) {
	rows, err := q.db.Query(ctx, listSchoolAdminsForSchool, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchoolAdminsForSchoolRow{}
	for rows.Next() {
		var i ListSchoolAdminsForSchoolRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.Role,
			&i.Status,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchoolsForAdmin = `-- name: ListSchoolsForAdmin :many
SELECT s.id, s.name, s.address, s.phone, s.status, s.created_at, s.updated_at
FROM schools s
INNER JOIN school_admins sa ON sa.school_id = s.id
WHERE sa.user_id = $1
ORDER BY s.created_at DESC
`

func (q *Queries) ListSchoolsForAdmin(ctx context.Context, userID uuid.UUID) ([]School, error) {
	rows, err := q.db.Query(ctx, listSchoolsForAdmin, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []School{}
	for rows.Next() {
		var i School
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSchoolAdmin = `-- name: RemoveSchoolAdmin :exec
DELETE FROM school_admins
WHERE school_id = $1 AND user_id = $2
`

type RemoveSchoolAdminParams struct {
	SchoolID uuid.UUID `json:"school_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveSchoolAdmin(ctx context.Context, arg RemoveSchoolAdminParams) error {
	_, err := q.db.Exec(ctx, removeSchoolAdmin, arg.SchoolID, arg.UserID)
	return err
}
