// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: streaming.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertCameraHealthEvent = `-- name: InsertCameraHealthEvent :one
INSERT INTO camera_health_events (
    id,
    camera_id,
    school_id,
    event_type,
    severity,
    message,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, camera_id, school_id, event_type, severity, message, metadata, created_at
`

type InsertCameraHealthEventParams struct {
	ID        uuid.UUID   `json:"id"`
	CameraID  uuid.UUID   `json:"camera_id"`
	SchoolID  uuid.UUID   `json:"school_id"`
	EventType string      `json:"event_type"`
	Severity  string      `json:"severity"`
	Message   pgtype.Text `json:"message"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) InsertCameraHealthEvent(ctx context.Context, arg InsertCameraHealthEventParams) (CameraHealthEvent, error) {
	row := q.db.QueryRow(ctx, insertCameraHealthEvent,
		arg.ID,
		arg.CameraID,
		arg.SchoolID,
		arg.EventType,
		arg.Severity,
		arg.Message,
		arg.Metadata,
	)
	var i CameraHealthEvent
	err := row.Scan(
		&i.ID,
		&i.CameraID,
		&i.SchoolID,
		&i.EventType,
		&i.Severity,
		&i.Message,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const insertWorkerHeartbeat = `-- name: InsertWorkerHeartbeat :one
INSERT INTO worker_heartbeats (
    id,
    worker_name,
    worker_type,
    status,
    metadata,
    last_seen_at
) VALUES (
    $1, $2, $3, $4, $5, NOW()
)
RETURNING id, worker_name, worker_type, status, metadata, last_seen_at, created_at
`

type InsertWorkerHeartbeatParams struct {
	ID         uuid.UUID `json:"id"`
	WorkerName string    `json:"worker_name"`
	WorkerType string    `json:"worker_type"`
	Status     string    `json:"status"`
	Metadata   []byte    `json:"metadata"`
}

func (q *Queries) InsertWorkerHeartbeat(ctx context.Context, arg InsertWorkerHeartbeatParams) (WorkerHeartbeat, error) {
	row := q.db.QueryRow(ctx, insertWorkerHeartbeat,
		arg.ID,
		arg.WorkerName,
		arg.WorkerType,
		arg.Status,
		arg.Metadata,
	)
	var i WorkerHeartbeat
	err := row.Scan(
		&i.ID,
		&i.WorkerName,
		&i.WorkerType,
		&i.Status,
		&i.Metadata,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveCamerasForStreaming = `-- name: ListActiveCamerasForStreaming :many
SELECT
    cam.id,
    cam.school_id,
    cam.classroom_id,
    cam.name,
    cam.encrypted_rtsp_url,
    cam.r2_live_path,
    cam.r2_recording_path,
    cam.default_quality,
    cam.status,
    cam.last_segment_at
FROM cameras cam
INNER JOIN schools s ON s.id = cam.school_id AND s.status = 'ACTIVE'
INNER JOIN classrooms cr ON cr.id = cam.classroom_id AND cr.status = 'ACTIVE'
INNER JOIN camera_stream_states css ON css.camera_id = cam.id AND css.desired_state = 'RUNNING'
WHERE cam.status IN ('ACTIVE', 'OFFLINE')
ORDER BY cam.name
`

type ListActiveCamerasForStreamingRow struct {
	ID               uuid.UUID          `json:"id"`
	SchoolID         uuid.UUID          `json:"school_id"`
	ClassroomID      pgtype.UUID        `json:"classroom_id"`
	Name             string             `json:"name"`
	EncryptedRtspUrl pgtype.Text        `json:"encrypted_rtsp_url"`
	R2LivePath       string             `json:"r2_live_path"`
	R2RecordingPath  pgtype.Text        `json:"r2_recording_path"`
	DefaultQuality   string             `json:"default_quality"`
	Status           string             `json:"status"`
	LastSegmentAt    pgtype.Timestamptz `json:"last_segment_at"`
}

func (q *Queries) ListActiveCamerasForStreaming(ctx context.Context) ([]ListActiveCamerasForStreamingRow, error) {
	rows, err := q.db.Query(ctx, listActiveCamerasForStreaming)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveCamerasForStreamingRow{}
	for rows.Next() {
		var i ListActiveCamerasForStreamingRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.ClassroomID,
			&i.Name,
			&i.EncryptedRtspUrl,
			&i.R2LivePath,
			&i.R2RecordingPath,
			&i.DefaultQuality,
			&i.Status,
			&i.LastSegmentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCameraStreamStatus = `-- name: UpdateCameraStreamStatus :exec
UPDATE cameras
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateCameraStreamStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateCameraStreamStatus(ctx context.Context, arg UpdateCameraStreamStatusParams) error {
	_, err := q.db.Exec(ctx, updateCameraStreamStatus, arg.ID, arg.Status)
	return err
}
