// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activateSubscription = `-- name: ActivateSubscription :one
UPDATE subscriptions
SET status = 'ACTIVE', ends_at = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, parent_id, school_id, status, starts_at, ends_at, created_at, updated_at
`

type ActivateSubscriptionParams struct {
	ID     uuid.UUID          `json:"id"`
	EndsAt pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) ActivateSubscription(ctx context.Context, arg ActivateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, activateSubscription, arg.ID, arg.EndsAt)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    id,
    parent_id,
    school_id,
    status,
    starts_at,
    ends_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, parent_id, school_id, status, starts_at, ends_at, created_at, updated_at
`

type CreateSubscriptionParams struct {
	ID       uuid.UUID          `json:"id"`
	ParentID uuid.UUID          `json:"parent_id"`
	SchoolID uuid.UUID          `json:"school_id"`
	Status   string             `json:"status"`
	StartsAt pgtype.Timestamptz `json:"starts_at"`
	EndsAt   pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ID,
		arg.ParentID,
		arg.SchoolID,
		arg.Status,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const extendSubscription = `-- name: ExtendSubscription :one
UPDATE subscriptions
SET ends_at = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, parent_id, school_id, status, starts_at, ends_at, created_at, updated_at
`

type ExtendSubscriptionParams struct {
	ID     uuid.UUID          `json:"id"`
	EndsAt pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) ExtendSubscription(ctx context.Context, arg ExtendSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, extendSubscription, arg.ID, arg.EndsAt)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveSubscriptionForParentSchool = `-- name: GetActiveSubscriptionForParentSchool :one
SELECT id, parent_id, school_id, status, starts_at, ends_at, created_at, updated_at
FROM subscriptions
WHERE parent_id = $1
  AND school_id = $2
  AND status IN ('ACTIVE', 'TRIAL')
  AND (ends_at IS NULL OR ends_at > NOW())
LIMIT 1
`

type GetActiveSubscriptionForParentSchoolParams struct {
	ParentID uuid.UUID `json:"parent_id"`
	SchoolID uuid.UUID `json:"school_id"`
}

func (q *Queries) GetActiveSubscriptionForParentSchool(ctx context.Context, arg GetActiveSubscriptionForParentSchoolParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscriptionForParentSchool, arg.ParentID, arg.SchoolID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, parent_id, school_id, status, starts_at, ends_at, created_at, updated_at FROM subscriptions WHERE id = $1
`

func (q *Queries) GetSubscription(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByParentSchool = `-- name: GetSubscriptionByParentSchool :one
SELECT id, parent_id, school_id, status, starts_at, ends_at, created_at, updated_at
FROM subscriptions
WHERE parent_id = $1 AND school_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetSubscriptionByParentSchoolParams struct {
	ParentID uuid.UUID `json:"parent_id"`
	SchoolID uuid.UUID `json:"school_id"`
}

func (q *Queries) GetSubscriptionByParentSchool(ctx context.Context, arg GetSubscriptionByParentSchoolParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByParentSchool, arg.ParentID, arg.SchoolID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasActiveSubscriptionForParentSchool = `-- name: HasActiveSubscriptionForParentSchool :one
SELECT EXISTS (
    SELECT 1
    FROM subscriptions
    WHERE parent_id = $1
      AND school_id = $2
      AND status IN ('ACTIVE', 'TRIAL')
      AND (ends_at IS NULL OR ends_at > NOW())
) AS exists
`

type HasActiveSubscriptionForParentSchoolParams struct {
	ParentID uuid.UUID `json:"parent_id"`
	SchoolID uuid.UUID `json:"school_id"`
}

func (q *Queries) HasActiveSubscriptionForParentSchool(ctx context.Context, arg HasActiveSubscriptionForParentSchoolParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveSubscriptionForParentSchool, arg.ParentID, arg.SchoolID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listSubscriptionsAdmin = `-- name: ListSubscriptionsAdmin :many
SELECT s.id, s.parent_id, s.school_id, s.status, s.starts_at, s.ends_at, s.created_at, s.updated_at, u.full_name AS parent_name, sch.name AS school_name
FROM subscriptions s
INNER JOIN users u ON u.id = s.parent_id
INNER JOIN schools sch ON sch.id = s.school_id
WHERE ($1::uuid[] IS NULL OR s.school_id = ANY($1::uuid[]))
  AND ($2::uuid IS NULL OR s.school_id = $2)
  AND ($3::uuid IS NULL OR s.parent_id = $3)
  AND ($4::text IS NULL OR s.status = $4)
ORDER BY s.created_at DESC
LIMIT $5
`

type ListSubscriptionsAdminParams struct {
	SchoolIds []uuid.UUID `json:"school_ids"`
	SchoolID  pgtype.UUID `json:"school_id"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Status    pgtype.Text `json:"status"`
	RowLimit  int32       `json:"row_limit"`
}

type ListSubscriptionsAdminRow struct {
	ID         uuid.UUID          `json:"id"`
	ParentID   uuid.UUID          `json:"parent_id"`
	SchoolID   uuid.UUID          `json:"school_id"`
	Status     string             `json:"status"`
	StartsAt   pgtype.Timestamptz `json:"starts_at"`
	EndsAt     pgtype.Timestamptz `json:"ends_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	ParentName string             `json:"parent_name"`
	SchoolName string             `json:"school_name"`
}

func (q *Queries) ListSubscriptionsAdmin(ctx context.Context, arg ListSubscriptionsAdminParams) ([]ListSubscriptionsAdminRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsAdmin,
		arg.SchoolIds,
		arg.SchoolID,
		arg.ParentID,
		arg.Status,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscriptionsAdminRow{}
	for rows.Next() {
		var i ListSubscriptionsAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.SchoolID,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentName,
			&i.SchoolName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByParent = `-- name: ListSubscriptionsByParent :many
SELECT s.id, s.parent_id, s.school_id, s.status, s.starts_at, s.ends_at, s.created_at, s.updated_at, sch.name AS school_name
FROM subscriptions s
INNER JOIN schools sch ON sch.id = s.school_id
WHERE s.parent_id = $1
ORDER BY s.created_at DESC
`

type ListSubscriptionsByParentRow struct {
	ID         uuid.UUID          `json:"id"`
	ParentID   uuid.UUID          `json:"parent_id"`
	SchoolID   uuid.UUID          `json:"school_id"`
	Status     string             `json:"status"`
	StartsAt   pgtype.Timestamptz `json:"starts_at"`
	EndsAt     pgtype.Timestamptz `json:"ends_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	SchoolName string             `json:"school_name"`
}

func (q *Queries) ListSubscriptionsByParent(ctx context.Context, parentID uuid.UUID) ([]ListSubscriptionsByParentRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsByParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscriptionsByParentRow{}
	for rows.Next() {
		var i ListSubscriptionsByParentRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.SchoolID,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SchoolName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsBySchool = `-- name: ListSubscriptionsBySchool :many
SELECT s.id, s.parent_id, s.school_id, s.status, s.starts_at, s.ends_at, s.created_at, s.updated_at, u.full_name AS parent_name, u.email AS parent_email, sch.name AS school_name
FROM subscriptions s
INNER JOIN users u ON u.id = s.parent_id
INNER JOIN schools sch ON sch.id = s.school_id
WHERE s.school_id = $1
  AND ($2::text IS NULL OR s.status = $2)
  AND ($3::uuid IS NULL OR s.parent_id = $3)
ORDER BY s.created_at DESC
`

type ListSubscriptionsBySchoolParams struct {
	SchoolID uuid.UUID   `json:"school_id"`
	Status   pgtype.Text `json:"status"`
	ParentID pgtype.UUID `json:"parent_id"`
}

type ListSubscriptionsBySchoolRow struct {
	ID          uuid.UUID          `json:"id"`
	ParentID    uuid.UUID          `json:"parent_id"`
	SchoolID    uuid.UUID          `json:"school_id"`
	Status      string             `json:"status"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ParentName  string             `json:"parent_name"`
	ParentEmail pgtype.Text        `json:"parent_email"`
	SchoolName  string             `json:"school_name"`
}

func (q *Queries) ListSubscriptionsBySchool(ctx context.Context, arg ListSubscriptionsBySchoolParams) ([]ListSubscriptionsBySchoolRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsBySchool, arg.SchoolID, arg.Status, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubscriptionsBySchoolRow{}
	for rows.Next() {
		var i ListSubscriptionsBySchoolRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.SchoolID,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentName,
			&i.ParentEmail,
			&i.SchoolName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :one
UPDATE subscriptions
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, parent_id, school_id, status, starts_at, ends_at, created_at, updated_at
`

type UpdateSubscriptionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionStatus, arg.ID, arg.Status)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
