// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    full_name,
    phone,
    email,
    password_hash,
    role,
    status,
    force_password_change,
    created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, full_name, phone, email, password_hash, role, status, force_password_change, password_changed_at, last_login_at, created_by_user_id, created_at, updated_at
`

type CreateUserParams struct {
	ID                  uuid.UUID   `json:"id"`
	FullName            string      `json:"full_name"`
	Phone               pgtype.Text `json:"phone"`
	Email               pgtype.Text `json:"email"`
	PasswordHash        pgtype.Text `json:"password_hash"`
	Role                string      `json:"role"`
	Status              string      `json:"status"`
	ForcePasswordChange bool        `json:"force_password_change"`
	CreatedByUserID     pgtype.UUID `json:"created_by_user_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.FullName,
		arg.Phone,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
		arg.ForcePasswordChange,
		arg.CreatedByUserID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ForcePasswordChange,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, phone, email, password_hash, role, status, force_password_change, password_changed_at, last_login_at, created_by_user_id, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ForcePasswordChange,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, phone, email, password_hash, role, status, force_password_change, password_changed_at, last_login_at, created_by_user_id, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ForcePasswordChange,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listManagedUsers = `-- name: ListManagedUsers :many
SELECT id, full_name, phone, email, password_hash, role, status, force_password_change, password_changed_at, last_login_at, created_by_user_id, created_at, updated_at FROM users
WHERE role IN ('SUPER_ADMIN', 'SCHOOL_ADMIN', 'TECHNICIAN')
ORDER BY created_at DESC
`

func (q *Queries) ListManagedUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listManagedUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Status,
			&i.ForcePasswordChange,
			&i.PasswordChangedAt,
			&i.LastLoginAt,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParents = `-- name: ListParents :many
SELECT id, full_name, phone, email, password_hash, role, status, force_password_change, password_changed_at, last_login_at, created_by_user_id, created_at, updated_at FROM users
WHERE role = 'PARENT'
ORDER BY created_at DESC
`

func (q *Queries) ListParents(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listParents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Status,
			&i.ForcePasswordChange,
			&i.PasswordChangedAt,
			&i.LastLoginAt,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserForcePasswordChange = `-- name: SetUserForcePasswordChange :one
UPDATE users
SET force_password_change = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, full_name, phone, email, password_hash, role, status, force_password_change, password_changed_at, last_login_at, created_by_user_id, created_at, updated_at
`

type SetUserForcePasswordChangeParams struct {
	ID                  uuid.UUID `json:"id"`
	ForcePasswordChange bool      `json:"force_password_change"`
}

func (q *Queries) SetUserForcePasswordChange(ctx context.Context, arg SetUserForcePasswordChangeParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserForcePasswordChange, arg.ID, arg.ForcePasswordChange)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ForcePasswordChange,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPasswordFull = `-- name: UpdateUserPasswordFull :one
UPDATE users
SET
    password_hash = $2,
    password_changed_at = NOW(),
    force_password_change = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, full_name, phone, email, password_hash, role, status, force_password_change, password_changed_at, last_login_at, created_by_user_id, created_at, updated_at
`

type UpdateUserPasswordFullParams struct {
	ID                  uuid.UUID   `json:"id"`
	PasswordHash        pgtype.Text `json:"password_hash"`
	ForcePasswordChange bool        `json:"force_password_change"`
}

func (q *Queries) UpdateUserPasswordFull(ctx context.Context, arg UpdateUserPasswordFullParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPasswordFull, arg.ID, arg.PasswordHash, arg.ForcePasswordChange)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ForcePasswordChange,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET
    full_name = $2,
    email = $3,
    phone = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, full_name, phone, email, password_hash, role, status, force_password_change, password_changed_at, last_login_at, created_by_user_id, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID       uuid.UUID   `json:"id"`
	FullName string      `json:"full_name"`
	Email    pgtype.Text `json:"email"`
	Phone    pgtype.Text `json:"phone"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.Phone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ForcePasswordChange,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, full_name, phone, email, password_hash, role, status, force_password_change, password_changed_at, last_login_at, created_by_user_id, created_at, updated_at
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role string    `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ForcePasswordChange,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, full_name, phone, email, password_hash, role, status, force_password_change, password_changed_at, last_login_at, created_by_user_id, created_at, updated_at
`

type UpdateUserStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.ForcePasswordChange,
		&i.PasswordChangedAt,
		&i.LastLoginAt,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
