// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQidR79-UfyapP5CZCtT2SG0-5IOyz6IA',
    appId: '1:315056141665:web:f1da29e774e64ce6ac4120',
    messagingSenderId: '315056141665',
    projectId: 'school-camera-72810',
    authDomain: 'school-camera-72810.firebaseapp.com',
    storageBucket: 'school-camera-72810.firebasestorage.app',
    measurementId: 'G-4KXVWBKS8Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtUsGIb84qJPd3QHSq-TRMnEeXUgjmclk',
    appId: '1:315056141665:android:6114f36cb30f593aac4120',
    messagingSenderId: '315056141665',
    projectId: 'school-camera-72810',
    storageBucket: 'school-camera-72810.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQFNhsE8VuAbnWXH8DX60DPOw2GuHaRxg',
    appId: '1:315056141665:ios:5182b11b6facc716ac4120',
    messagingSenderId: '315056141665',
    projectId: 'school-camera-72810',
    storageBucket: 'school-camera-72810.firebasestorage.app',
    iosBundleId: 'com.iglooks.schoolcamera.schoolCamera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQFNhsE8VuAbnWXH8DX60DPOw2GuHaRxg',
    appId: '1:315056141665:ios:5182b11b6facc716ac4120',
    messagingSenderId: '315056141665',
    projectId: 'school-camera-72810',
    storageBucket: 'school-camera-72810.firebasestorage.app',
    iosBundleId: 'com.iglooks.schoolcamera.schoolCamera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQidR79-UfyapP5CZCtT2SG0-5IOyz6IA',
    appId: '1:315056141665:web:50a56142ef487caeac4120',
    messagingSenderId: '315056141665',
    projectId: 'school-camera-72810',
    authDomain: 'school-camera-72810.firebaseapp.com',
    storageBucket: 'school-camera-72810.firebasestorage.app',
    measurementId: 'G-J52X0GN8NV',
  );

}