// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    id,
    user_id,
    school_id,
    classroom_id,
    camera_id,
    child_id,
    device_id,
    action,
    ip_address,
    user_agent,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, user_id, school_id, classroom_id, camera_id, child_id, device_id, action, ip_address, user_agent, metadata, created_at
`

type CreateAuditLogParams struct {
	ID          uuid.UUID   `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	SchoolID    pgtype.UUID `json:"school_id"`
	ClassroomID pgtype.UUID `json:"classroom_id"`
	CameraID    pgtype.UUID `json:"camera_id"`
	ChildID     pgtype.UUID `json:"child_id"`
	DeviceID    pgtype.UUID `json:"device_id"`
	Action      string      `json:"action"`
	IpAddress   pgtype.Text `json:"ip_address"`
	UserAgent   pgtype.Text `json:"user_agent"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ID,
		arg.UserID,
		arg.SchoolID,
		arg.ClassroomID,
		arg.CameraID,
		arg.ChildID,
		arg.DeviceID,
		arg.Action,
		arg.IpAddress,
		arg.UserAgent,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SchoolID,
		&i.ClassroomID,
		&i.CameraID,
		&i.ChildID,
		&i.DeviceID,
		&i.Action,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
