// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
    id,
    user_id,
    device_name,
    device_fingerprint,
    status,
    last_seen_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, device_name, device_fingerprint, status, last_seen_at, fcm_token, push_platform, notifications_enabled, notification_preferences, fcm_token_updated_at, app_version, created_at
`

type CreateDeviceParams struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	DeviceName        pgtype.Text        `json:"device_name"`
	DeviceFingerprint string             `json:"device_fingerprint"`
	Status            string             `json:"status"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.ID,
		arg.UserID,
		arg.DeviceName,
		arg.DeviceFingerprint,
		arg.Status,
		arg.LastSeenAt,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceName,
		&i.DeviceFingerprint,
		&i.Status,
		&i.LastSeenAt,
		&i.FcmToken,
		&i.PushPlatform,
		&i.NotificationsEnabled,
		&i.NotificationPreferences,
		&i.FcmTokenUpdatedAt,
		&i.AppVersion,
		&i.CreatedAt,
	)
	return i, err
}

const disableDeviceNotifications = `-- name: DisableDeviceNotifications :one
UPDATE devices
SET notifications_enabled = FALSE
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, device_name, device_fingerprint, status, last_seen_at, fcm_token, push_platform, notifications_enabled, notification_preferences, fcm_token_updated_at, app_version, created_at
`

type DisableDeviceNotificationsParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DisableDeviceNotifications(ctx context.Context, arg DisableDeviceNotificationsParams) (Device, error) {
	row := q.db.QueryRow(ctx, disableDeviceNotifications, arg.ID, arg.UserID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceName,
		&i.DeviceFingerprint,
		&i.Status,
		&i.LastSeenAt,
		&i.FcmToken,
		&i.PushPlatform,
		&i.NotificationsEnabled,
		&i.NotificationPreferences,
		&i.FcmTokenUpdatedAt,
		&i.AppVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceByFingerprint = `-- name: GetDeviceByFingerprint :one
SELECT id, user_id, device_name, device_fingerprint, status, last_seen_at, fcm_token, push_platform, notifications_enabled, notification_preferences, fcm_token_updated_at, app_version, created_at FROM devices
WHERE user_id = $1 AND device_fingerprint = $2
`

type GetDeviceByFingerprintParams struct {
	UserID            uuid.UUID `json:"user_id"`
	DeviceFingerprint string    `json:"device_fingerprint"`
}

func (q *Queries) GetDeviceByFingerprint(ctx context.Context, arg GetDeviceByFingerprintParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByFingerprint, arg.UserID, arg.DeviceFingerprint)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceName,
		&i.DeviceFingerprint,
		&i.Status,
		&i.LastSeenAt,
		&i.FcmToken,
		&i.PushPlatform,
		&i.NotificationsEnabled,
		&i.NotificationPreferences,
		&i.FcmTokenUpdatedAt,
		&i.AppVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceByIDForUser = `-- name: GetDeviceByIDForUser :one
SELECT id, user_id, device_name, device_fingerprint, status, last_seen_at, fcm_token, push_platform, notifications_enabled, notification_preferences, fcm_token_updated_at, app_version, created_at FROM devices
WHERE id = $1 AND user_id = $2
`

type GetDeviceByIDForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetDeviceByIDForUser(ctx context.Context, arg GetDeviceByIDForUserParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByIDForUser, arg.ID, arg.UserID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceName,
		&i.DeviceFingerprint,
		&i.Status,
		&i.LastSeenAt,
		&i.FcmToken,
		&i.PushPlatform,
		&i.NotificationsEnabled,
		&i.NotificationPreferences,
		&i.FcmTokenUpdatedAt,
		&i.AppVersion,
		&i.CreatedAt,
	)
	return i, err
}

const listPushEnabledDevicesForUser = `-- name: ListPushEnabledDevicesForUser :many
SELECT id, user_id, device_name, device_fingerprint, status, last_seen_at, fcm_token, push_platform, notifications_enabled, notification_preferences, fcm_token_updated_at, app_version, created_at FROM devices
WHERE user_id = $1
  AND status = 'ACTIVE'
  AND notifications_enabled = TRUE
  AND fcm_token IS NOT NULL
  AND length(trim(fcm_token)) > 0
`

func (q *Queries) ListPushEnabledDevicesForUser(ctx context.Context, userID uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listPushEnabledDevicesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceName,
			&i.DeviceFingerprint,
			&i.Status,
			&i.LastSeenAt,
			&i.FcmToken,
			&i.PushPlatform,
			&i.NotificationsEnabled,
			&i.NotificationPreferences,
			&i.FcmTokenUpdatedAt,
			&i.AppVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDevices = `-- name: ListUserDevices :many
SELECT id, user_id, device_name, device_fingerprint, status, last_seen_at, fcm_token, push_platform, notifications_enabled, notification_preferences, fcm_token_updated_at, app_version, created_at FROM devices
WHERE user_id = $1
ORDER BY last_seen_at DESC NULLS LAST, created_at DESC
`

func (q *Queries) ListUserDevices(ctx context.Context, userID uuid.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listUserDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeviceName,
			&i.DeviceFingerprint,
			&i.Status,
			&i.LastSeenAt,
			&i.FcmToken,
			&i.PushPlatform,
			&i.NotificationsEnabled,
			&i.NotificationPreferences,
			&i.FcmTokenUpdatedAt,
			&i.AppVersion,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceLastSeen = `-- name: UpdateDeviceLastSeen :one
UPDATE devices
SET last_seen_at = $3, device_name = COALESCE($4, device_name)
WHERE user_id = $1 AND device_fingerprint = $2
RETURNING id, user_id, device_name, device_fingerprint, status, last_seen_at, fcm_token, push_platform, notifications_enabled, notification_preferences, fcm_token_updated_at, app_version, created_at
`

type UpdateDeviceLastSeenParams struct {
	UserID            uuid.UUID          `json:"user_id"`
	DeviceFingerprint string             `json:"device_fingerprint"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	DeviceName        pgtype.Text        `json:"device_name"`
}

func (q *Queries) UpdateDeviceLastSeen(ctx context.Context, arg UpdateDeviceLastSeenParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDeviceLastSeen,
		arg.UserID,
		arg.DeviceFingerprint,
		arg.LastSeenAt,
		arg.DeviceName,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceName,
		&i.DeviceFingerprint,
		&i.Status,
		&i.LastSeenAt,
		&i.FcmToken,
		&i.PushPlatform,
		&i.NotificationsEnabled,
		&i.NotificationPreferences,
		&i.FcmTokenUpdatedAt,
		&i.AppVersion,
		&i.CreatedAt,
	)
	return i, err
}

const updateDeviceLastSeenByID = `-- name: UpdateDeviceLastSeenByID :exec
UPDATE devices
SET last_seen_at = $2
WHERE id = $1 AND user_id = $3
`

type UpdateDeviceLastSeenByIDParams struct {
	ID         uuid.UUID          `json:"id"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	UserID     uuid.UUID          `json:"user_id"`
}

func (q *Queries) UpdateDeviceLastSeenByID(ctx context.Context, arg UpdateDeviceLastSeenByIDParams) error {
	_, err := q.db.Exec(ctx, updateDeviceLastSeenByID, arg.ID, arg.LastSeenAt, arg.UserID)
	return err
}

const updateDeviceNotificationPreferences = `-- name: UpdateDeviceNotificationPreferences :one
UPDATE devices
SET notification_preferences = $3
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, device_name, device_fingerprint, status, last_seen_at, fcm_token, push_platform, notifications_enabled, notification_preferences, fcm_token_updated_at, app_version, created_at
`

type UpdateDeviceNotificationPreferencesParams struct {
	ID                      uuid.UUID       `json:"id"`
	UserID                  uuid.UUID       `json:"user_id"`
	NotificationPreferences json.RawMessage `json:"notification_preferences"`
}

func (q *Queries) UpdateDeviceNotificationPreferences(ctx context.Context, arg UpdateDeviceNotificationPreferencesParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDeviceNotificationPreferences, arg.ID, arg.UserID, arg.NotificationPreferences)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceName,
		&i.DeviceFingerprint,
		&i.Status,
		&i.LastSeenAt,
		&i.FcmToken,
		&i.PushPlatform,
		&i.NotificationsEnabled,
		&i.NotificationPreferences,
		&i.FcmTokenUpdatedAt,
		&i.AppVersion,
		&i.CreatedAt,
	)
	return i, err
}

const updateDevicePushToken = `-- name: UpdateDevicePushToken :one
UPDATE devices
SET
    fcm_token = $3,
    push_platform = $4,
    app_version = $5,
    notifications_enabled = $6,
    fcm_token_updated_at = NOW(),
    last_seen_at = NOW(),
    device_name = COALESCE($7, device_name)
WHERE user_id = $1 AND device_fingerprint = $2
RETURNING id, user_id, device_name, device_fingerprint, status, last_seen_at, fcm_token, push_platform, notifications_enabled, notification_preferences, fcm_token_updated_at, app_version, created_at
`

type UpdateDevicePushTokenParams struct {
	UserID               uuid.UUID   `json:"user_id"`
	DeviceFingerprint    string      `json:"device_fingerprint"`
	FcmToken             pgtype.Text `json:"fcm_token"`
	PushPlatform         pgtype.Text `json:"push_platform"`
	AppVersion           pgtype.Text `json:"app_version"`
	NotificationsEnabled bool        `json:"notifications_enabled"`
	DeviceName           pgtype.Text `json:"device_name"`
}

func (q *Queries) UpdateDevicePushToken(ctx context.Context, arg UpdateDevicePushTokenParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevicePushToken,
		arg.UserID,
		arg.DeviceFingerprint,
		arg.FcmToken,
		arg.PushPlatform,
		arg.AppVersion,
		arg.NotificationsEnabled,
		arg.DeviceName,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceName,
		&i.DeviceFingerprint,
		&i.Status,
		&i.LastSeenAt,
		&i.FcmToken,
		&i.PushPlatform,
		&i.NotificationsEnabled,
		&i.NotificationPreferences,
		&i.FcmTokenUpdatedAt,
		&i.AppVersion,
		&i.CreatedAt,
	)
	return i, err
}

const updateDevicePushTokenByID = `-- name: UpdateDevicePushTokenByID :one
UPDATE devices
SET
    fcm_token = $3,
    push_platform = $4,
    app_version = $5,
    notifications_enabled = $6,
    fcm_token_updated_at = NOW(),
    last_seen_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, device_name, device_fingerprint, status, last_seen_at, fcm_token, push_platform, notifications_enabled, notification_preferences, fcm_token_updated_at, app_version, created_at
`

type UpdateDevicePushTokenByIDParams struct {
	ID                   uuid.UUID   `json:"id"`
	UserID               uuid.UUID   `json:"user_id"`
	FcmToken             pgtype.Text `json:"fcm_token"`
	PushPlatform         pgtype.Text `json:"push_platform"`
	AppVersion           pgtype.Text `json:"app_version"`
	NotificationsEnabled bool        `json:"notifications_enabled"`
}

func (q *Queries) UpdateDevicePushTokenByID(ctx context.Context, arg UpdateDevicePushTokenByIDParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevicePushTokenByID,
		arg.ID,
		arg.UserID,
		arg.FcmToken,
		arg.PushPlatform,
		arg.AppVersion,
		arg.NotificationsEnabled,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceName,
		&i.DeviceFingerprint,
		&i.Status,
		&i.LastSeenAt,
		&i.FcmToken,
		&i.PushPlatform,
		&i.NotificationsEnabled,
		&i.NotificationPreferences,
		&i.FcmTokenUpdatedAt,
		&i.AppVersion,
		&i.CreatedAt,
	)
	return i, err
}
