// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parent_superapp_links.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createParentSuperAppLink = `-- name: CreateParentSuperAppLink :one
INSERT INTO parent_superapp_links (
    id, parent_id, school_id, super_app_user_id, status
) VALUES (
    $1, $2, $3, $4, 'active'
)
RETURNING id, parent_id, school_id, super_app_user_id, status, linked_at, revoked_at, created_at, updated_at
`

type CreateParentSuperAppLinkParams struct {
	ID             uuid.UUID `json:"id"`
	ParentID       uuid.UUID `json:"parent_id"`
	SchoolID       uuid.UUID `json:"school_id"`
	SuperAppUserID uuid.UUID `json:"super_app_user_id"`
}

func (q *Queries) CreateParentSuperAppLink(ctx context.Context, arg CreateParentSuperAppLinkParams) (ParentSuperappLink, error) {
	row := q.db.QueryRow(ctx, createParentSuperAppLink,
		arg.ID,
		arg.ParentID,
		arg.SchoolID,
		arg.SuperAppUserID,
	)
	var i ParentSuperappLink
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.SuperAppUserID,
		&i.Status,
		&i.LinkedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveParentSuperAppLinkBySuperAppUser = `-- name: GetActiveParentSuperAppLinkBySuperAppUser :one
SELECT id, parent_id, school_id, super_app_user_id, status, linked_at, revoked_at, created_at, updated_at FROM parent_superapp_links
WHERE super_app_user_id = $1
  AND status = 'active'
LIMIT 1
`

func (q *Queries) GetActiveParentSuperAppLinkBySuperAppUser(ctx context.Context, superAppUserID uuid.UUID) (ParentSuperappLink, error) {
	row := q.db.QueryRow(ctx, getActiveParentSuperAppLinkBySuperAppUser, superAppUserID)
	var i ParentSuperappLink
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.SuperAppUserID,
		&i.Status,
		&i.LinkedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParentSuperAppLinkByParent = `-- name: GetParentSuperAppLinkByParent :one
SELECT id, parent_id, school_id, super_app_user_id, status, linked_at, revoked_at, created_at, updated_at FROM parent_superapp_links
WHERE parent_id = $1
  AND status = 'active'
`

func (q *Queries) GetParentSuperAppLinkByParent(ctx context.Context, parentID uuid.UUID) (ParentSuperappLink, error) {
	row := q.db.QueryRow(ctx, getParentSuperAppLinkByParent, parentID)
	var i ParentSuperappLink
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.SuperAppUserID,
		&i.Status,
		&i.LinkedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParentSuperAppLinkBySuperAppUserAndSchool = `-- name: GetParentSuperAppLinkBySuperAppUserAndSchool :one
SELECT id, parent_id, school_id, super_app_user_id, status, linked_at, revoked_at, created_at, updated_at FROM parent_superapp_links
WHERE super_app_user_id = $1
  AND school_id = $2
  AND status = 'active'
`

type GetParentSuperAppLinkBySuperAppUserAndSchoolParams struct {
	SuperAppUserID uuid.UUID `json:"super_app_user_id"`
	SchoolID       uuid.UUID `json:"school_id"`
}

func (q *Queries) GetParentSuperAppLinkBySuperAppUserAndSchool(ctx context.Context, arg GetParentSuperAppLinkBySuperAppUserAndSchoolParams) (ParentSuperappLink, error) {
	row := q.db.QueryRow(ctx, getParentSuperAppLinkBySuperAppUserAndSchool, arg.SuperAppUserID, arg.SchoolID)
	var i ParentSuperappLink
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.SuperAppUserID,
		&i.Status,
		&i.LinkedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listParentSuperAppLinksBySchool = `-- name: ListParentSuperAppLinksBySchool :many
SELECT psl.id, psl.parent_id, psl.school_id, psl.super_app_user_id, psl.status, psl.linked_at, psl.revoked_at, psl.created_at, psl.updated_at, u.full_name AS parent_name
FROM parent_superapp_links psl
JOIN users u ON u.id = psl.parent_id
WHERE psl.school_id = $1
ORDER BY psl.linked_at DESC
`

type ListParentSuperAppLinksBySchoolRow struct {
	ID             uuid.UUID          `json:"id"`
	ParentID       uuid.UUID          `json:"parent_id"`
	SchoolID       uuid.UUID          `json:"school_id"`
	SuperAppUserID uuid.UUID          `json:"super_app_user_id"`
	Status         string             `json:"status"`
	LinkedAt       pgtype.Timestamptz `json:"linked_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ParentName     string             `json:"parent_name"`
}

func (q *Queries) ListParentSuperAppLinksBySchool(ctx context.Context, schoolID uuid.UUID) ([]ListParentSuperAppLinksBySchoolRow, error) {
	rows, err := q.db.Query(ctx, listParentSuperAppLinksBySchool, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParentSuperAppLinksBySchoolRow{}
	for rows.Next() {
		var i ListParentSuperAppLinksBySchoolRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.SchoolID,
			&i.SuperAppUserID,
			&i.Status,
			&i.LinkedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeParentSuperAppLink = `-- name: RevokeParentSuperAppLink :one
UPDATE parent_superapp_links
SET status = 'revoked',
    revoked_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, parent_id, school_id, super_app_user_id, status, linked_at, revoked_at, created_at, updated_at
`

func (q *Queries) RevokeParentSuperAppLink(ctx context.Context, id uuid.UUID) (ParentSuperappLink, error) {
	row := q.db.QueryRow(ctx, revokeParentSuperAppLink, id)
	var i ParentSuperappLink
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.SuperAppUserID,
		&i.Status,
		&i.LinkedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
