// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parent_invitation_codes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createParentInvitationCode = `-- name: CreateParentInvitationCode :one
INSERT INTO parent_invitation_codes (
    id, parent_id, school_id, code_hash, code_prefix, status, expires_at, created_by
) VALUES (
    $1, $2, $3, $4, $5, 'active', $6, $7
)
RETURNING id, parent_id, school_id, code_hash, code_prefix, status, expires_at, used_at, used_by_super_app_user_id, revoked_at, created_by, created_at, updated_at
`

type CreateParentInvitationCodeParams struct {
	ID         uuid.UUID          `json:"id"`
	ParentID   uuid.UUID          `json:"parent_id"`
	SchoolID   uuid.UUID          `json:"school_id"`
	CodeHash   string             `json:"code_hash"`
	CodePrefix string             `json:"code_prefix"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateParentInvitationCode(ctx context.Context, arg CreateParentInvitationCodeParams) (ParentInvitationCode, error) {
	row := q.db.QueryRow(ctx, createParentInvitationCode,
		arg.ID,
		arg.ParentID,
		arg.SchoolID,
		arg.CodeHash,
		arg.CodePrefix,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i ParentInvitationCode
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.CodeHash,
		&i.CodePrefix,
		&i.Status,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedBySuperAppUserID,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParentInvitationCodeByHash = `-- name: GetParentInvitationCodeByHash :one
SELECT id, parent_id, school_id, code_hash, code_prefix, status, expires_at, used_at, used_by_super_app_user_id, revoked_at, created_by, created_at, updated_at FROM parent_invitation_codes
WHERE code_hash = $1
`

func (q *Queries) GetParentInvitationCodeByHash(ctx context.Context, codeHash string) (ParentInvitationCode, error) {
	row := q.db.QueryRow(ctx, getParentInvitationCodeByHash, codeHash)
	var i ParentInvitationCode
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.CodeHash,
		&i.CodePrefix,
		&i.Status,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedBySuperAppUserID,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParentInvitationCodeByID = `-- name: GetParentInvitationCodeByID :one
SELECT id, parent_id, school_id, code_hash, code_prefix, status, expires_at, used_at, used_by_super_app_user_id, revoked_at, created_by, created_at, updated_at FROM parent_invitation_codes
WHERE id = $1
`

func (q *Queries) GetParentInvitationCodeByID(ctx context.Context, id uuid.UUID) (ParentInvitationCode, error) {
	row := q.db.QueryRow(ctx, getParentInvitationCodeByID, id)
	var i ParentInvitationCode
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.CodeHash,
		&i.CodePrefix,
		&i.Status,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedBySuperAppUserID,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listParentInvitationCodesByParent = `-- name: ListParentInvitationCodesByParent :many
SELECT id, parent_id, school_id, code_hash, code_prefix, status, expires_at, used_at, used_by_super_app_user_id, revoked_at, created_by, created_at, updated_at FROM parent_invitation_codes
WHERE parent_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListParentInvitationCodesByParent(ctx context.Context, parentID uuid.UUID) ([]ParentInvitationCode, error) {
	rows, err := q.db.Query(ctx, listParentInvitationCodesByParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParentInvitationCode{}
	for rows.Next() {
		var i ParentInvitationCode
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.SchoolID,
			&i.CodeHash,
			&i.CodePrefix,
			&i.Status,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.UsedBySuperAppUserID,
			&i.RevokedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentInvitationCodesBySchool = `-- name: ListParentInvitationCodesBySchool :many
SELECT id, parent_id, school_id, code_hash, code_prefix, status, expires_at, used_at, used_by_super_app_user_id, revoked_at, created_by, created_at, updated_at FROM parent_invitation_codes
WHERE school_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListParentInvitationCodesBySchool(ctx context.Context, schoolID uuid.UUID) ([]ParentInvitationCode, error) {
	rows, err := q.db.Query(ctx, listParentInvitationCodesBySchool, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParentInvitationCode{}
	for rows.Next() {
		var i ParentInvitationCode
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.SchoolID,
			&i.CodeHash,
			&i.CodePrefix,
			&i.Status,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.UsedBySuperAppUserID,
			&i.RevokedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markParentInvitationCodeUsed = `-- name: MarkParentInvitationCodeUsed :one
UPDATE parent_invitation_codes
SET status = 'used',
    used_at = NOW(),
    used_by_super_app_user_id = $2,
    updated_at = NOW()
WHERE id = $1
  AND status = 'active'
RETURNING id, parent_id, school_id, code_hash, code_prefix, status, expires_at, used_at, used_by_super_app_user_id, revoked_at, created_by, created_at, updated_at
`

type MarkParentInvitationCodeUsedParams struct {
	ID                   uuid.UUID   `json:"id"`
	UsedBySuperAppUserID pgtype.UUID `json:"used_by_super_app_user_id"`
}

func (q *Queries) MarkParentInvitationCodeUsed(ctx context.Context, arg MarkParentInvitationCodeUsedParams) (ParentInvitationCode, error) {
	row := q.db.QueryRow(ctx, markParentInvitationCodeUsed, arg.ID, arg.UsedBySuperAppUserID)
	var i ParentInvitationCode
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.CodeHash,
		&i.CodePrefix,
		&i.Status,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedBySuperAppUserID,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeActiveParentInvitationCodesForParent = `-- name: RevokeActiveParentInvitationCodesForParent :exec
UPDATE parent_invitation_codes
SET status = 'revoked',
    revoked_at = NOW(),
    updated_at = NOW()
WHERE parent_id = $1
  AND school_id = $2
  AND status = 'active'
`

type RevokeActiveParentInvitationCodesForParentParams struct {
	ParentID uuid.UUID `json:"parent_id"`
	SchoolID uuid.UUID `json:"school_id"`
}

func (q *Queries) RevokeActiveParentInvitationCodesForParent(ctx context.Context, arg RevokeActiveParentInvitationCodesForParentParams) error {
	_, err := q.db.Exec(ctx, revokeActiveParentInvitationCodesForParent, arg.ParentID, arg.SchoolID)
	return err
}

const revokeParentInvitationCode = `-- name: RevokeParentInvitationCode :one
UPDATE parent_invitation_codes
SET status = 'revoked',
    revoked_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, parent_id, school_id, code_hash, code_prefix, status, expires_at, used_at, used_by_super_app_user_id, revoked_at, created_by, created_at, updated_at
`

func (q *Queries) RevokeParentInvitationCode(ctx context.Context, id uuid.UUID) (ParentInvitationCode, error) {
	row := q.db.QueryRow(ctx, revokeParentInvitationCode, id)
	var i ParentInvitationCode
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.CodeHash,
		&i.CodePrefix,
		&i.Status,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedBySuperAppUserID,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
