// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_requests.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentRequest = `-- name: CreatePaymentRequest :one
INSERT INTO school_camera_payment_requests (
    id,
    parent_id,
    school_id,
    super_app_user_id,
    amount_minor,
    currency,
    months,
    status,
    idempotency_key,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 'pending', $8, $9
)
RETURNING id, parent_id, school_id, super_app_user_id, amount_minor, currency, months, status, super_app_payment_reference, idempotency_key, paid_at, completed_at, expires_at, created_at, updated_at
`

type CreatePaymentRequestParams struct {
	ID             uuid.UUID          `json:"id"`
	ParentID       uuid.UUID          `json:"parent_id"`
	SchoolID       uuid.UUID          `json:"school_id"`
	SuperAppUserID uuid.UUID          `json:"super_app_user_id"`
	AmountMinor    int64              `json:"amount_minor"`
	Currency       string             `json:"currency"`
	Months         int32              `json:"months"`
	IdempotencyKey string             `json:"idempotency_key"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePaymentRequest(ctx context.Context, arg CreatePaymentRequestParams) (SchoolCameraPaymentRequest, error) {
	row := q.db.QueryRow(ctx, createPaymentRequest,
		arg.ID,
		arg.ParentID,
		arg.SchoolID,
		arg.SuperAppUserID,
		arg.AmountMinor,
		arg.Currency,
		arg.Months,
		arg.IdempotencyKey,
		arg.ExpiresAt,
	)
	var i SchoolCameraPaymentRequest
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.SuperAppUserID,
		&i.AmountMinor,
		&i.Currency,
		&i.Months,
		&i.Status,
		&i.SuperAppPaymentReference,
		&i.IdempotencyKey,
		&i.PaidAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireStalePaymentRequests = `-- name: ExpireStalePaymentRequests :execrows
UPDATE school_camera_payment_requests
SET status     = 'expired',
    updated_at = NOW()
WHERE status = 'pending'
  AND expires_at < NOW()
`

func (q *Queries) ExpireStalePaymentRequests(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, expireStalePaymentRequests)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPaymentRequest = `-- name: GetPaymentRequest :one
SELECT id, parent_id, school_id, super_app_user_id, amount_minor, currency, months, status, super_app_payment_reference, idempotency_key, paid_at, completed_at, expires_at, created_at, updated_at FROM school_camera_payment_requests WHERE id = $1
`

func (q *Queries) GetPaymentRequest(ctx context.Context, id uuid.UUID) (SchoolCameraPaymentRequest, error) {
	row := q.db.QueryRow(ctx, getPaymentRequest, id)
	var i SchoolCameraPaymentRequest
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.SuperAppUserID,
		&i.AmountMinor,
		&i.Currency,
		&i.Months,
		&i.Status,
		&i.SuperAppPaymentReference,
		&i.IdempotencyKey,
		&i.PaidAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentRequestByIdempotencyKey = `-- name: GetPaymentRequestByIdempotencyKey :one
SELECT id, parent_id, school_id, super_app_user_id, amount_minor, currency, months, status, super_app_payment_reference, idempotency_key, paid_at, completed_at, expires_at, created_at, updated_at FROM school_camera_payment_requests WHERE idempotency_key = $1
`

func (q *Queries) GetPaymentRequestByIdempotencyKey(ctx context.Context, idempotencyKey string) (SchoolCameraPaymentRequest, error) {
	row := q.db.QueryRow(ctx, getPaymentRequestByIdempotencyKey, idempotencyKey)
	var i SchoolCameraPaymentRequest
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.SuperAppUserID,
		&i.AmountMinor,
		&i.Currency,
		&i.Months,
		&i.Status,
		&i.SuperAppPaymentReference,
		&i.IdempotencyKey,
		&i.PaidAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentRequestByReference = `-- name: GetPaymentRequestByReference :one
SELECT id, parent_id, school_id, super_app_user_id, amount_minor, currency, months, status, super_app_payment_reference, idempotency_key, paid_at, completed_at, expires_at, created_at, updated_at FROM school_camera_payment_requests
WHERE super_app_payment_reference = $1
LIMIT 1
`

func (q *Queries) GetPaymentRequestByReference(ctx context.Context, superAppPaymentReference pgtype.Text) (SchoolCameraPaymentRequest, error) {
	row := q.db.QueryRow(ctx, getPaymentRequestByReference, superAppPaymentReference)
	var i SchoolCameraPaymentRequest
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.SuperAppUserID,
		&i.AmountMinor,
		&i.Currency,
		&i.Months,
		&i.Status,
		&i.SuperAppPaymentReference,
		&i.IdempotencyKey,
		&i.PaidAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentRequestCompleted = `-- name: MarkPaymentRequestCompleted :one
UPDATE school_camera_payment_requests
SET completed_at = NOW(),
    updated_at   = NOW()
WHERE id = $1
RETURNING id, parent_id, school_id, super_app_user_id, amount_minor, currency, months, status, super_app_payment_reference, idempotency_key, paid_at, completed_at, expires_at, created_at, updated_at
`

func (q *Queries) MarkPaymentRequestCompleted(ctx context.Context, id uuid.UUID) (SchoolCameraPaymentRequest, error) {
	row := q.db.QueryRow(ctx, markPaymentRequestCompleted, id)
	var i SchoolCameraPaymentRequest
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.SuperAppUserID,
		&i.AmountMinor,
		&i.Currency,
		&i.Months,
		&i.Status,
		&i.SuperAppPaymentReference,
		&i.IdempotencyKey,
		&i.PaidAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentRequestPaid = `-- name: MarkPaymentRequestPaid :one
UPDATE school_camera_payment_requests
SET status = 'paid',
    super_app_payment_reference = $2,
    paid_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND status = 'pending'
RETURNING id, parent_id, school_id, super_app_user_id, amount_minor, currency, months, status, super_app_payment_reference, idempotency_key, paid_at, completed_at, expires_at, created_at, updated_at
`

type MarkPaymentRequestPaidParams struct {
	ID                       uuid.UUID   `json:"id"`
	SuperAppPaymentReference pgtype.Text `json:"super_app_payment_reference"`
}

func (q *Queries) MarkPaymentRequestPaid(ctx context.Context, arg MarkPaymentRequestPaidParams) (SchoolCameraPaymentRequest, error) {
	row := q.db.QueryRow(ctx, markPaymentRequestPaid, arg.ID, arg.SuperAppPaymentReference)
	var i SchoolCameraPaymentRequest
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.SchoolID,
		&i.SuperAppUserID,
		&i.AmountMinor,
		&i.Currency,
		&i.Months,
		&i.Status,
		&i.SuperAppPaymentReference,
		&i.IdempotencyKey,
		&i.PaidAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
